### ISSUE TITLE
Flux CD Executor Plugin

### ISSUE THREAD

**Issue by brampling** [kubeshop/botkube#1016]
## Overview

Botkube has existing support for `kubectl` and `helm`. We need to add support for the Flux CD CLI to run Flux commands through Botkube.

## Acceptance Criteria

- [ ] Flux executor plugin should have the same experience (commands, flags) as Flux CD CLI
- [ ] Implement Flux CD plugin for Botkube
    - interactivity is out of scope
    - Must-have commands: reconcile, suspend, resume
- [ ] Design a configuration structure for the Flux executor plugin
- [ ] Document it in plugins folder under the main Botkube repository.

Stretch:

- [ ]  - Additional commands are nice-to-have but not part of this scope, we should make sure they can be added lateradd `helm history` command
- [ ] Document under `docs.botkube.io`

## Reason

Flux CD support has been requested by the community and is useful for quickly managing Flux deployments from chat tools. See: https://github.com/fluxcd/flux2/discussions/3561

## Notes

1. Implement flux executor - small wrapper over `x` capabilities
  -  support `flux diff`
  - integration tests are out of scope
  - prepare documentation

Story flow:

On GitHub pull request creation/update, notify about `flux diff` for a given PR.

1. GitHub source plugin: get incoming event and pass it to a given source
  - support file path filter
  - support GitHub apps token and PAT
  - use polling to get GitHub events (we'll fit in the rate limits for sure)
  - ask for only updated stuff (modified header)
3. Post a message about new PR with handy commands underneath
   - include `flux diff` in the dropdown
4. Run `flux diff`
   - this command will be "wrapped" by us so that we can pass PR data (link/pr number/repo etc., whatever we need)
   - try to support coloring
6. Flux executor outputs the command in interactive way
   - include "Post as a GitHub coment"
7. GH executor takes input and posts as PR comment

**Comment by mashby2022** [comment]
@mszostok and I met with the Flux Devrel and there's community interest. How should we proceed to put fit this into the engineering calendar
