### ISSUE TITLE
Botkube killed when plugin download takes too long

### ISSUE THREAD

**Issue by 1d9akash** [kubeshop/botkube#1027]
## Description

Tried To Setup Botkube In Minikube. Faced Some Issues:
Setting Up Bot In Slack Went Smoothly,
Faced Issue In Setting Up Botkube In Minikube Cluster, The Bot Was Deployed Successully:
![image](https://user-images.githubusercontent.com/127375633/228222942-aa748b70-e6d6-4f4b-8645-d8b64efe8d56.png)
But When I Tried To Ping The Bot In Slack, It Didnt Worked.
Thanks To The Community Members For Solving The Issue

## Expected behavior
I Thought That There Might Be An Issue In Passing The Environment Variables & Might Be Issue With Helm

## Actual behavior

The Issue Is With The Helm Charts,
After Trying Various Solutions To Troubleshoot
Setting Up This `--set 'executors.helm.botkube/helm.enabled'=false` in Installation Procedure
Resolved My Issue.

Once Again Thanks To The Team For Solving The Issue.

**Comment by pkosiec** [comment]
See the full thread here: https://botkube.slack.com/archives/C01CR1KS55K/p1679989389837669

The reason is that the Botkube Pod were killed as the Helm plugin download took too much time.
