### ISSUE TITLE
Make the Help message more streamlined 

### ISSUE THREAD

**Issue by lpetkov** [kubeshop/botkube#1046]
This is a proposal for a more streamlined Help message design.
**Reason:** we already have a lot going on and as we keep adding more and more features to document this message is only going to grow.

Notes:
* I think there is no need for `show config` to be part of this message, people can refer to the docs if they want to edit the full config file
* Let's refer to docs for features/plugins instead of trying to cram commands and help about each thing.
* We can either link to our web docs or send an additional help message when the user presses, for example, "kubectl help"
* Leave notification options and the ping as they are because they are good to have at people's disposal initially and they serve as examples that people can actually type commands @ the bot.

![image](https://user-images.githubusercontent.com/31132490/232818820-9ef38474-a712-4342-aa48-57066b20d554.png)

**Comment by pkosiec** [comment]
![image](https://github.com/kubeshop/botkube/assets/7155799/74018654-9370-4496-b8ac-8c326580dedd)

FYI I actually started working on that last Thursday afternoon and I've fit in the estimation 👍

**Comment by lpetkov** [comment]
One improvement I remember discussing with @mszostok months ago is to detect whether notifications are on and only display a [Disable] or [Enable] toggle button instead of the current three buttons. That wasn't possible back then, but if it is now, go for it!

Also, it's currently (and in the design above) somewhat unclear whether notifications are ON or OFF at the moment. Something as simple as changing the title to "Notifications (Enabled)" could be an improvement!

**Comment by pkosiec** [comment]
Welcome back, Lacho! Unfortunately right now IMO it is still not feasible, but I think it still a great improvement 👍
