### ISSUE TITLE
Hope to add more log for local debugging more easily

### ISSUE THREAD

**Issue by NPOSUI** [kubeshop/botkube#1059]
### For example, slack cannot receive the return message if the channel name is not configured correctly on the local configuration.
For this issue, botkube only returns a simple error. 
  Like this: "while handling message: while sending message: while reading Slack response: empty response  bot=SocketSlack commGroup=default-group"
  I spent a lot of time solving this problem before finally realizing that the locally configured channel name was “Botkube”, while the remote channel name was “botkube”, which caused a mismatch in the program and resulted in the slack channel not being able to obtain the return message. Maybe it's just that my programming skills are relatively poor, haha.
  So, I hope to add debug log here: "botkube/pkg/execute/executor.go", line 120.
  ```go
   if !e.conversation.IsAuthenticated {
       e.log.Errorf("debug log here...")
       return empty
   }
  ```
Botkube version: release-1.0
##### This is my first attempt to submit a issue, just hoping to save time for others to troubleshoot issues.

**Comment by pkosiec** [comment]
Hey @NPOSUI,
Thank you for reporting this. You're absolutely right - there should be a debug log in this place. We'll add this in Botkube 1.0.1, which will be out in a next few days. Cheers!

**Comment by NPOSUI** [comment]
Thank you for handling my issue. I believe it will help others.

**Comment by NPOSUI** [comment]
close
