### ISSUE TITLE
Migration CLI

### ISSUE THREAD

**Issue by josefkarasek** [kubeshop/botkube#1067]
## Overview

Migration CLI that helps Botkube users migrate to Botkube Cloud.

Easy to use, single purpose binary distributed via brew and public release on github.

## Acceptance Criteria

* [x] Use existing `botkube` repository
    - if possible keep git history
    - rename `botkube` binary to `botkube-agent`
    - add new entrypoint (`cli`)
    - Figure out the final name - `bk` / `bkctl` / `bro-ctl`? It'll be general Botkube CLI, not only for cloud
* [x] Copy GraphQL models from Cloud with a script - go-getter? 
* [x] Implement login and migration features
     - Include missing stuff: aliases
     - Add banner in CLI what is not supported
         - Discover Botkube version and say if it's not supported (do it at your own risk)
         - RBAC will be defaulted
         - plugins will be used from default repository
         - only Slack, Mattermost, Discord are supported
* [x] Ensure error handling is in place
* [x] Tests (focus on feature parity)
* [x] CI pipelines + release infrastructure (linux + macos, docker image)
    - ~~Publish it in GCS release as they need to be always up to date~~
* [x] Basic documentation (on botkube docs)
    - Custom "Getting started" doc - something like https://capact.io/docs/cli/getting-started
    - Generate commands from Cobra on botkube repo
    - Generate docs from Cobra and also synchronize it to docs with manual script?
* [ ] Implement UI pages on Botkube Cloud
    - [ ] Error state (https://www.figma.com/file/QNcHtrYHsRdjOhTfClMmmE/Botkube-SaaS?type=design&node-id=409-17173&t=jMNOZjtGpWp2u0Tc-0)?
* [ ] Issue first release?
   - Consider using GCS to publish CLI?

## Follow-up 

https://github.com/kubeshop/botkube/issues/1125

## Notes

The command could be scoped under `cloud` -> e.g. `bkctl cloud migrate`/ `bkctl cloud create --from=/--from-existing`?

## Out of scope - later

- RBAC - until it is supported on Botkube Cloud side
- Handle third party plugins

## Reason

Onboarding experience with Botkube Cloud

**Comment by pkosiec** [comment]
This will be followed-up in #1125 👍
