### ISSUE TITLE
Update events every 30 minutes

### ISSUE THREAD

**Issue by kriptor** [kubeshop/botkube#1081]
## Description

Using `Botkube v1.0.1` inside `Kubernetes v1.26.5` (Digitalocean managed).
Using `socketSlack`.
Using unmodified sources `k8s-all-events` and `k8s-recommendation-events`.
Using unmodified `k8s-default-tools` with only `botkube/kubectl` enabled.

I observe a strange behavior.. after the start of Botkube, **every 30 minutes** I get Slack notifications about all the **daemonsets, statefulsets, deployments** and **jobs** inside the cluster as if they are all being updated. Those notifications never contain any diffs. If I do `kubectl get event -A` right after I get those Slack notifications, there is nothing there.. when I do regular deploys of my stuff I can see events using kubectl and I get Slack notifications via Botkube.

## Expected behavior

I would like to get notifications only when something is actually happening.

## Actual behavior

Getting

:bulb: apps/v1/statefulsets updated
:bulb: apps/v1/daemonsets updated
:bulb: batch/v1/jobs updated
:bulb: apps/v1/deployments updated

for all resources of these types inside the cluster every 30 minutes when nothing is actually being updated... at least not that I know of or can see via `kubectl get event -A`.

## Steps to reproduce

Not really sure, but it's happening on both of my clusters.

##
Any idea how tho troubleshoot this would be great, for I'm kind of stuck with `k8s-err-events` for now.

**Comment by kriptor** [comment]
Upgraded to botkube v1.1.0, but unfortunately still the same.

**Comment by pkosiec** [comment]
Hi @kriptor, 
Sorry for late response. Can you show the configuration you used with all sensitive data removed? Do you use `updateSetting.includeDiff`option?

**Comment by trevorlauder** [comment]
I'm experiencing this as well since upgrading to `1.0.1`, previously on `0.18.0` without this issue.

```
- type: apps/v1/deployments
  namespaces:
    include:
      - ".*"
    exclude:
      - cluster-overprovisioner
  event:
    types:
      - create
      - update
      - delete
      - error
  updateSetting:
    includeDiff: true
    fields:
      - spec.template.spec.containers[*].image
      - status.availableReplicas

**Comment by libsamek** [comment]
We are also experiencing the same behavior and it's quite inconvenient, to say the least.
Example of config:
```
          - type: apps/v1/statefulsets
            event:
              types:
                - create
                - update
                - delete
                - error
            updateSetting:
              includeDiff: true
              fields:
                - spec.template.spec.containers[*].image
                - spec.replicas
```

**Comment by pkosiec** [comment]
Thank you all for your reports. We'll look into the issue and try to fix it soon 👍 We will post all updates in this thread.
