### ISSUE TITLE
Discord integration: while getting channel name for ID: Missing Access

### ISSUE THREAD

**Issue by rossigee** [kubeshop/botkube#1082]
## Description

I have followed the Discord integration tutorial. I have double-checked the OAuth URL permissions against the screenshot in the docs.

However, the bot crashes with a 'Missing Access' error. It's not clear what permission is missing or how to fix it.

## Expected behavior

The bot to start up as expected.

## Actual behavior

Pod goes into CrashLoopBackoff. Logs contain...

```
...
while creating Discord bot: while creating Discord channels config: while getting channel name for ID "927205489793391234": HTTP 403 Forbidden, {"message": "Missing Access", "code": 50001}
```

## Steps to reproduce

Follow Discord integration steps in documentation.

**Comment by DanielAtanasovski** [comment]
Received a similar error but a `401` instead. Enabling the the `Read Messages/View Channels` permission and inviting the bot onto the server again solved it for me.

```
while creating Discord bot: while creating Discord channels config: while getting channel name for ID "**********": HTTP 401 Unauthorized, {"message": "401: Unauthorized", "code": 0}
```

![image](https://github.com/kubeshop/botkube/assets/40650169/dc32f3a0-70bc-4000-850c-e0c943a4962c)

**Comment by rossigee** [comment]
This ended up being a misconfiguration on my part. It turned out that I'd invited the bot to the wrong 'test' channel. I had two similarly names test channels on my server, so the bot did not have any permissions on the channel it was trying to join.
