### ISSUE TITLE
Productionize Keptn Plugin

### ISSUE THREAD

**Issue by huseyinbabal** [kubeshop/botkube#1089]
Productionize keptn plugin, pr is [here](https://github.com/kubeshop/botkube/pull/1050), and the doc is [here](https://botkube.io/blog/implementing-your-own-botkube-plugin-a-real-life-use-case)

## AC

- documentation on docs website
- review and merge keptn plugin to Botkube
- make sure it is accessible from cloud

This is needed for Keptn Community Call on July 26th.

### Later
- we can investigate keptn lifecycle toolkit

**Comment by mashby2022** [comment]
are we still on track to do this

**Comment by huseyinbabal** [comment]
@mashby2022 yep, I am on it right now.

**Comment by agardnerIT** [comment]
Hi all, thank you so much for your presentation on the Keptn community call last night! Powerful stuff!

As I discussed, integrating into Keptn Lifecycle Toolkit we could start with:

## 1. Show me all the KLT-enabled namespaces

```
kubectl get namespaces -o=jsonpath='{.items[?(@.metadata.annotations.keptn\.sh/lifecycle-toolkit=="enabled")].metadata.name}'
```

## 2. Tell Keptn to start monitoring a namespace

```
# Assume ns called `demo` exists
kubectl annotate namespace demo keptn.sh/lifecycle-toolkit=enabled
```

**Comment by pkosiec** [comment]
(closing as it was already moved to done)
