### ISSUE TITLE
MS Teams integration fails to parse Channel ID from message

### ISSUE THREAD

**Issue by josefkarasek** [kubeshop/botkube#1103]
## Description

Command `show config` causes botkube to upload a file to OneDrive, which fails with:

```
time="2023-06-19T11:42:44Z" level=info msg="Teams Channel ID not found. Using default ID...`" bot="MS Teams" commGroup=default-group
```

It appears that a [string constant](https://github.com/kubeshop/botkube/blob/main/pkg/bot/teams.go#L504) on MS side has changed.

## Expected behavior

Botkube can upload files to OneDrive and commands such as `show config` work.

## Actual behavior

Nothing happens. Error appears in Botkube logs.

## Steps to reproduce

1. Install Botkube with MS Teams bot
2. Run `show config`
3. Error is in pod logs

**Comment by mszostok** [comment]
The Teams platform is not supported since [v1.14](https://github.com/kubeshop/botkube/releases/tag/v1.14.0).
