### ISSUE TITLE
UUID constantly regenerated when using ArgoCD

### ISSUE THREAD

**Issue by trevorlauder** [kubeshop/botkube#1120]
## Description

The change introduced in https://github.com/kubeshop/botkube/pull/1077 and released in `1.1.0` causes the helm chart to constantly detect and apply changes because the UUID changes on every helm template run.  Because the random UUID is used in a key name rather than the value, I don't think we can exclude it from ArgoCD.

## Expected behavior

UUID needs to stay the same between helm template runs.

## Actual behavior

UUID changes causing the ArgoCD app to constantly be out of sync and redeploying.

**Comment by mszostok** [comment]
Hi @trevorlauder 

Thanks for reporting this issue. We will fix it and publish a patch release ASAP.
