### ISSUE TITLE
Cannot find kubectl command UI in Slack Message that Botkube Bot created

### ISSUE THREAD

**Issue by kworkbee** [kubeshop/botkube#1166]
## Description

When I upgraded Botkube to v1.2.0 (Helm), Slack Message that botkube bot created contains kubectl command UI but there seems to be no disable config in `values.yaml`

## Expected behavior

`value.yaml` changes should remove the kubectl command UI from the slack message.

## Actual behavior

Red box (Image Below) should be removed

![image](https://github.com/kubeshop/botkube/assets/18034626/8e7bf89f-0da7-47b1-a789-3dfdd776e7c3)

**Comment by pkosiec** [comment]
Hi @kworkbee,
please take a look at the docs here: https://docs.botkube.io/configuration/source/kubernetes#syntax

As you can see, there's an option to configure which commands are displayed under notifications. Specifically, these fields:

```yaml
  "my-events-config":
    # ...
    botkube/kubernetes:
      # ...
      config:
        # ...
        commands:
          # -- Configures which verbs are available in actionable items.
          verbs: ["api-resources", "api-versions", "cluster-info", "describe", "explain", "get", "logs", "top"]
          # -- Configure which resources are available in actionable items.
          resources:
            [
              "deployments",
              "pods",
              "namespaces",
              "daemonsets",
              "statefulsets",
              "storageclasses",
              "nodes",
              "configmaps",
              "services",
              "ingresses",
            ]
```

Try to pass empty list of verbs and resources, and it should work 👍

Let me know if that helps. Cheers!

**Comment by kworkbee** [comment]
@pkosiec I couldn't check the document because I only saw Github. I finally solved the issue. Thank you for your kind reply! :)

**Comment by pkosiec** [comment]
Glad you resolved your issue! Enjoy using Botkube! 🚀
