### ISSUE TITLE
Handling k8s empty resource list properly

### ISSUE THREAD

**Issue by huseyinbabal** [kubeshop/botkube#1173]
## Problem
Each kubernetes event goes through a series of filters and also a set of available commands are generated to attache it to platform notification message. On command generation, we get  the available resource list for kubernetes, and there is a legacy logic in kubernetes go client for handling empty response. For this legaciness, we have specific error handling mechanism in kubernetes plugins as shown below;

```go
func shouldIgnoreResourceListError(err error) bool {
	groupDiscoFailedErr, ok := err.(*discovery.ErrGroupDiscoveryFailed)
	if !ok {
		return false
	}

	for _, currentErr := range groupDiscoFailedErr.Groups {
		// Unfortunately there isn't a nicer way to do this.
		// See https://github.com/kubernetes/client-go/blob/release-1.25/discovery/cached/memory/memcache.go#L228
		if strings.Contains(currentErr.Error(), "received empty response for") {
			// ignore it as it isn't necessarily an error
			continue
		}

		return false
	}

	return true
} 
```

After kubernetes 1.25, they have changed this strategy on client-go project, and they now return `received empty response for` instead of `received empty response for`. 

[Kubernetes Go Client 1.25](https://github.com/kubernetes/client-go/blob/release-1.25/discovery/cached/memory/memcache.go#L228)
[Kubernetes Go Client 1.26](https://github.com/kubernetes/client-go/blob/ee237183876174af7eea996cbbaa639d89b974fa/discovery/cached/memory/memcache.go#L71)

One of Botkube users just reported recently that, once they changed their EKS cluster version, they stopped seeing the error events from kubernetes cluster. Here is the related logs

```
{"level":"debug","logger":"stdout","msg":"\u001b[31mERRO\u001b[0m[2023-08-04T06:39:08Z] while rendering message from event: %!w(*fmt.wrapError=\u0026{while getting commands for event: while getting resource list from K8s cluster: unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: received empty response for: custom.metrics.k8s.io/v1beta1, custom.metrics.k8s.io/v1beta2: received empty response for: custom.metrics.k8s.io/v1beta2 0xc000493300}) ","plugin":"botkube/kubernetes","time":"2023-08-04T06:39:08Z"}
```
## Acceptance Criteria
- Find a proper error handling mechanism for empty resource list
   - Prepare error list/map and check if the error matches one of them
- Include it in 1.3.1 release

**Comment by songyanping** [comment]
@pkosiec I did not have this issue when deploying on K8S V1.24. Is it because botkube V1.0 does not support K8S V1.18?

**Comment by songyanping** [comment]
Kubernetes Version: v1.18.8
BotKube Version: v1.0

**Error message**
![1](https://github.com/kubeshop/botkube/assets/17720358/30e78163-0bb4-46d5-9ad8-4ef3fe4f40e4)
