### ISSUE TITLE
Botkube Cloud official walk through demos/ use cases

### ISSUE THREAD

**Issue by mashby2022** [kubeshop/botkube#1180]
Hi all, 

We briefly discussed how the eng team can be more involved in the GTM strategy. I need some help making some demo/ walkthrough videos for Bk cloud features and possible configurations. 

---

# Updated scope (agreed with Kelly and Maria):

Create a multi-cluster enviroment demo:
1. create 2-3 clusters
1. connect them with Teams
1. set default cluster for a given channel
1. receive some app crash error from e.g. dev env
1. debug it by showcasing basic functionality, getting responses from all of the clusters at once, etc.).
1. optionally show audit logs / disabling notifications? if that makes sense

**Comment by pkosiec** [comment]
One of the demo we can record is about the ArgoCD plugin:
See the internal conversation and a dry run: https://kubeshop.slack.com/archives/C03MRCX7UE9/p1694621395522669

**Comment by pkosiec** [comment]
Just raw videos:
- Helm
  - e.g. helm install, helm upgrade, helm rollback
- Prometheus
---
- Configuration + show plugin in action - build the config in Cloud UI

**Comment by pkosiec** [comment]
Currently the task is blocked as we still need to figure out what we should focus on as a part of the task. See the discussion: https://kubeshop.slack.com/archives/C04L84V0UBH/p1705319067366139

**Comment by pkosiec** [comment]
The raw recording is in review.
See the thread in Slack: https://kubeshop.slack.com/archives/C03MRCX7UE9/p1706020828970459
