### ISSUE TITLE
Release Botkube 1.3.0

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube#1181]
## Overview

This task aggregates all the to-dos which should be done when it comes to the release.

## AC
- [x] Go through the release process instruction and release new Botkube (https://docs.botkube.io/community/contribute/release)
- [x] Describe any breaking changes in the GitHub release (see the issues with `breaking` label)
- [x] Test the release candidate. Include:
    - Manual tests for Slack interactivity
    - Test telemetry
    - Aggregate and coordinate the manual testing described previously (e.g. https://github.com/kubeshop/botkube/issues/904, https://github.com/kubeshop/botkube/issues/957, https://github.com/kubeshop/botkube/issues/1094)

**Comment by huseyinbabal** [comment]
## Release activities
- [ ] Ensure that all security vulnerabilities are fixed or mitigated
  
  * assignee:
- [ ] Cut initial release candidate  for `v1.3.0`
  
  * assignee: 
- [ ] Finalize release the `v1.3.0`
  
  * assignee:
- [ ]  Test Socket Slack
  
  * test all interactive buttons/modals
  * assignee: 
- [ ]  Test Cloud Slack
  
  * test all interactive buttons/modals
  * assignee: 
- [ ]  Test Mattermost
  
  * assignee: 
- [ ]  Test Discord
  
  * assignee:  
- [ ]  Test MS Teams
  
  * assignee: 

- [ ] Test sinks:
   - Test Elasticsearch
   - Test Webhook
  
   assignee: 
- [ ]  Test Telemetry
   * test also telemetry from Cloud Slack.
  * assignee:
- [ ] Check if we described all breaking changes in the release summary and if it's rendered correctly.
  
  * assignee: team

- [ ] Test Prometheus
      assignee:  

- [ ] Test helm plugin [docs](https://github.com/kubeshop/botkube/tree/main/cmd/executor/helm)
  
  * assignee:

**Other:**

* :hourglass_flowing_sand: Prepare the release notes
  
  * assignee:@brampling
* :hourglass_flowing_sand: Create a blog post and cross-post it (e.g. Medium, Dev.to)
  
  * assignee: @brampling 
* :hourglass_flowing_sand: Share the news on social media (e.g. Reddit, Hacker News, LinkedIn, Twitter, Slack)
  
  * assignee: @brampling

**Comment by huseyinbabal** [comment]
@brampling Feel free to close ticket once you feel comfortable about the tasks under `Other`

**Comment by pkosiec** [comment]
Closing as the other release activities are tracked in different place 👍
