### ISSUE TITLE
couldn't get current server API group list: <nil>

### ISSUE THREAD

**Issue by songyanping** [kubeshop/botkube#1189]
Expected behavior:
I expected BotKube v1.0 to work without errors while running on Kubernetes v1.18.8.

Actual behavior:
However, I encountered the following error message:
`level=error msg="E0816 04:10:46.618915      80 memcache.go:189] couldn't get current server API group list: <nil>" logger=stderr plugin=botkube/kubernetes`

Steps to reproduce:

1. Deploy BotKube v1.0 on a Kubernetes cluster running v1.18.8.
2. Observe the logs generated by BotKube.

Additional Information:

- Kubernetes Version: v1.18.8
- BotKube Version: v1.0

Description:
I am running a Kubernetes cluster with version v1.18.8, and I deployed BotKube version v1.0 to monitor the cluster. However, I encountered an error in the logs with the following 
![image](https://github.com/kubeshop/botkube/assets/17720358/74eed108-5eda-440a-9a74-0a5972e0ffef)

**Comment by pkosiec** [comment]
Hey @songyanping, I think this is related to this one: https://github.com/kubeshop/botkube/issues/1173. Please follow #1173 for status updated. Hopefully we'll be able to fix it soon. Cheers!
