### ISSUE TITLE
Release Botkube Helm chart for the latest `main`

### ISSUE THREAD

**Issue by mszostok** [kubeshop/botkube#1203]
## Overview

On each new commit to the `main` branch release latest Botkube Helm chart.

## Acceptance Criteria

- [x] create a new GCS `botkube-latest-main-charts`

- [x] release the latest helm chart from the `main` branch
  - [x] do that on each commit only if it modifies the chart directory
  - [x] use a GitHub Action with a strategy where the older runs are canceled and replaced by the new one
- [x] change the latest image tag from `v9.99.9-dev` to `main-{last_7_sha_digits}` 
   - push two tags? both `latest-main` and `main-{sha}`?
- [x] Update repo URL in: 
  - https://github.com/kubeshop/botkube-cloud/blob/main/botkube-cloud-backend/e2e/config_sync/config_sync_discord_test.go#L50
  - https://github.com/kubeshop/botkube-cloud/blob/main/botkube-cloud-backend/e2e/config_sync/e2e_config_sync_slack_test.go#L328
- [x] Use matrix strategy to run the tests in parallel:
   **tests:**
     - cloud slack e2e test (cloud-side)
     - migration test (open-source)
   **helm charts:**
     - latest-main helm chart
     - latest stable
- [x] Make sure that we have an easy way to install it using `botkube install` command. For example `botkube install --version=@latest-main`
- [x] Ensure migration tests + Cloud Slack E2E Dev tests (run on `main`) work properly

## Reason

We install the latest Botkube agent in other repositories and we need to be able to install it without actually cloning the whole `botkube` repository.

## Notes

You can see an example implementation here: https://github.com/capactio/capact/blob/69774163d4d3cdbb5aaf45bed4e235a0e2440260/hack/release-charts.sh#L19

However, if more scripting will be needed consider using Go instead of bash.

**Comment by huseyinbabal** [comment]
@mszostok any motivation of using gcs? Here there is a demo version of gh-pages https://github.com/huseyinbabal/helm-charts/tree/gh-pages, wdyt about continue to use it?

**Comment by mszostok** [comment]
@huseyinbabal not sure what you mean by the gh-pages demo? Is it possible to have 2 GitHub pages on separate branches?

We already use the gh-pages to host our official (stable) Helm charts, see:
- https://github.com/kubeshop/botkube/tree/gh-pages
- https://charts.botkube.io/

So the reason behind that is that we cannot use the GitHub release, the gh-pages I would like to keep clean and not to be mixed with the latest ones from `main` (can be error-prone, like, overriding, removing other charts, etc.). The next widely used is GCS, that was the reason I suggested that. 

We can also consider Google Artifact Registry, but I don't think that it's necessary. Plugins are also [stored on GCS](https://github.com/kubeshop/botkube/blob/6c853734270d9b06df9f98b078b74d00c403cb7d/.github/workflows/upload-plugins.yaml#L16), so that will keep us with the same approach here, meaning that it will be easier to maintain.

**Comment by huseyinbabal** [comment]
Ok got it. Since we already publish rc releases I thought that we can also release main branch releases there. Yep GCS flow would be more isolated and clean
