### ISSUE TITLE
Prepare Botkube AKS cluster for Azure Back to sessions 

### ISSUE THREAD

**Issue by mashby2022** [kubeshop/botkube#1224]
Hi all, 
The Azure Back to School session is on September 23 but I need to submit some prerecorded content in advance. 
I need some help getting an AKS cluster set up to demo and making sure Teams works for a small demo of Bk functionality. 

Does the deadline of 9/15 work? 

## AC

- Create AKS cluster
   - Do we need the AKS cluster really? Will Maria showcase anything related to AKS?
   - Contact Blair for account

- Make sure we have a public endpoint for MS Teams
   - If this is too hard, we can fallback to different comm platform (Discord?)
- Install Botkube with MS Teams enabled

## Follow-ups

For later: getting started guide for AKS

**Comment by huseyinbabal** [comment]
You can refer to https://github.com/kubeshop/botkube-azure-tf for all the details to see how setup Botkube demo in Azure automatically.
