### ISSUE TITLE
Improve ArgoCD source plugin after dog-fooding

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube#1240]
## Description

Based on our dog fooding figure out the scope of ArgoCD plugin improvements. Confirm the scope inside the team.

### Ideas

- Add ArgoCD executor which is a ArgoCD CLI wrapped, which makes able to e.g. force resync the app
- support commands like:
          - `logs`
          - ~`describe app`~ Already there
          - `force re-sync`
          - other:
             - GitHub diff link URL
             - restart pods kubectl command
             - ~Argo UI URL  (?)~ Already there
- validate request body in a generic way (in incoming webhook handler based on JSON schema)
- useful filters to ignore spammy/not relevant events
       Notes:
       - https://argoproj.github.io/argo-events/sensors/filters/intro/ 
       - https://github.com/argoproj/argo-events/tree/master/examples/sensors
    
- work on the message format to make it more user-friendly
     - if possible in the notification, include :
       - what version was is being deployed (`v1.2.0 -> v1.2.1`)
       - commit Author
       - GitHub diff link, e.g. https://github.com/kubeshop/botkube/compare/main...b95411580e
- fix Typo in  Application botkube-cloud-backend has ben successfully synced

###
Blocked by #1239

**Comment by josefkarasek** [comment]
Summary from dogfooding in [original issue](https://github.com/kubeshop/botkube/issues/1239#issuecomment-1770547545).
