### ISSUE TITLE
Clarification regarding BotKube's support policy

### ISSUE THREAD

**Issue by ishaqkhattana** [kubeshop/botkube#1283]
Hey 👋 

I'm sorry if this isn't the right place but I needed some help with BotKube's support policy. 
I understand that the [archived versions](https://docs.botkube.io/versions/#archived) listen in the documentation are not supported anymore and it's a safe assumption that the versions prior to these aren't either. I wanted to know if the [previous versions](https://docs.botkube.io/versions/#previous) are supported or is it just the latest major.minor release that is supported at any given time. Is there any such support policy that BotKube follows? As this would help us loads in planning our upgrades.

TIA

**Comment by shazib-summar** [comment]
bump.

I had the same question

**Comment by pkosiec** [comment]
Hi,
As Botkube Cloud services have been discontinued (read the blog post [here](https://botkube.io/blog/announcing-end-of-life-for-botkube-cloud)), Botkube support is now fully community-driven. There's no guarantee that bug fixes introduced in the latest versions will be backported to previous ones so it's better to keep Botkube up-to-date.

Cheers!
