### ISSUE TITLE
Add kubesec-scan support to BotKube

### ISSUE THREAD

**Issue by PrasadG193** [kubeshop/botkube#129]
**Is your feature request related to a problem? Please describe.**
BotKube should scan Kubernetes resources with [kubesec.io](https://github.com/controlplaneio/kubesec) and send report to the user when a resource is created

**Describe the solution you'd like**
BotKube should have a configuration flag (something like `kubesec-scan=true/false`)  through which we can enable/disable the feature

**Comment by PrasadG193** [comment]
@aananthraj JFYI, we are thinking categorizing and writing filters for the rules mentioned here: https://kubesec.io/basics/. That will give up more flexibility to disable/enable checks and have well-documented messages in the notifications

**Comment by aananthraj** [comment]
I would like to add few points here.

> we are thinking categorizing and writing filters for the rules mentioned here

Instead we could use the kubesec go pkg which is readily available. 

 **Reference**:
https://github.com/controlplaneio/kubesec/blob/c09700148b299b61d06b392031f6e1eada4be543/pkg/server/server.go#L98

**Comment by PrasadG193** [comment]
@aananthraj yes, we can write a filter to run this scan if it doesn't take much time to run. By default we should disable the filter. If use want, they can enable it using `@BotKube filters` command

**Comment by aananthraj** [comment]
@PrasadG193 It's like Kubesec has cli inbuilt. 
So we can just install kubesec binary inside the docker container and use kubesec commands directly (instead of creating a seperate filter)
```
@botkube kubesec scan k8s-deployment.yaml
```

**Comment by PrasadG193** [comment]
I think if it doesn't cause much overhead, better to run it as a filter. I think it just checks specs and does some validation just like we do in our filter. And one may not do a scan on every resource.

**Comment by mahendrabagul** [comment]
FYI, I have started working on this issue.

**Comment by A-kanksh-a** [comment]
FYI, I have started working on the issue.

Using [kube-scan](https://github.com/octarinesec/kube-scan) will be a better solution.  [kubesec.io](https://kubesec.io/) scans for resources of kind Pod, DaemonSet, Deployment, StatefulSet and ignore the others.

[kube-scan](https://github.com/octarinesec/kube-scan) looks for each resource per namespace. For this, We can add a Botkube Configuration flag like which would give calculated risk for each resource

```
@Botkube scan                                                                                   `
```

**Comment by A-kanksh-a** [comment]
- [kube-scan](https://github.com/octarinesec/kube-scan) re-scans resources in all namespaces every 24 hours. Thus, if you want to get an up-to-date risk score (e.g. after installing a new app or resources), you need to restart or wait. Botkube is a notification system, we should get the risk as soon as the resource is created.

- Also while scanning acquires a lock on the resources to check for risk within the cluster, So if we have multiple bots doing [kube-scan](https://github.com/octarinesec/kube-scan) then there would be load on server.

- Considering these, kube-scan doesn't fit with the BotKube model

**Comment by pkosiec** [comment]
Hi,
Thank you for your input.  With Botkube 1.0+ extensibility, it's easy to create plugins for virtually any software. I'll close the issue for now as we don't plan to support `kubesec-scan` anytime soon. Cheers!
