### ISSUE TITLE
Add support to perform a vulnerability scan on container images

### ISSUE THREAD

**Issue by PrasadG193** [kubeshop/botkube#130]
**Is your feature request related to a problem? Please describe.**
BotKube should perform a vulnerability scan on the container images when pod is created and report CVE report to the user

**Describe the solution you'd like**
- We can use [Clair](https://github.com/coreos/clair) to perform vulnerability static analysis container images
- BotKube should have ability to disable/enable this feature through config flags

**Comment by aananthraj** [comment]
I would like to add some points here. 

- Implementing this feature as an "on demand vulnerability scan" using botkube commands, would be nice.
- Running scans on all pods by default, would lead to repetive scaning of images, for instance during scaling of replias, and we might need a mechanism to know if the image was scanned already.

**Comment by PrasadG193** [comment]
@aananthraj totally agree with you. This will also add the overhead of deploying Clair as a part for BotKube deployment, we need to search for the better option if there is any

**Comment by aananthraj** [comment]
Yes @PrasadG193 , I guess we could create/excute a kubernetes job for this instead of creating a permanent clair deployment of clair. The same holds good for #129. Let me know your opinion..?

**Comment by PrasadG193** [comment]
Yeah, that is also one way
