### ISSUE TITLE
Write a dev-related blog post

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube#1317]
## Overview

To do: Agree with @mashby2022 on the blog post topic.

**Comment by mashby2022** [comment]
Update from  GTM: 
make a stripped down version of the GEC tutorial, take about multi-cluster support in Teams, feature AKS in the tutorial

**Comment by mashby2022** [comment]
I added an outline: https://docs.google.com/document/d/1BuNdMl8MZvPYkQrnLp7owV0QrwFSXzEFHnJB25fi1jQ/edit?usp=sharing
