### ISSUE TITLE
Disable interactive commands

### ISSUE THREAD

**Issue by olfway** [kubeshop/botkube#1326]
## Overview

I would like to use botkube as a monitoring tool without any interactive commnds

## Acceptance Criteria

- [ ] Option in helm chart to disable interactive commands

## Reason

We don't want to give permissions to run any commands in cluster via slack

**Comment by pkosiec** [comment]
Hi @olfway,
Yes, you can disable the interactive commands and this is already possible.
Each source has their own configuration. For Kubernetes source, setting `sources.your-source-name.botkube/kubernetes.config.commands.verbs` to empty array `[]`
for the Kubernetes source should do the trick. You can do this via Helm's `--set` command (e.g. `--set sources.k8s-err-events.botkube/kubernetes.config.commands.verbs=[]`), or, if you use Botkube Cloud, via UI (YAML editor / UI form). Here's the full configuration for the Kubernetes source:
https://docs.botkube.io/configuration/source/kubernetes#syntax

Let me know if that helps!

**Comment by olfway** [comment]
Thanks, it works!

I was looking mostly in chart's values.yaml and missed that commands list
