### ISSUE TITLE
Update keptn plugin deps

### ISSUE THREAD

**Issue by mszostok** [kubeshop/botkube#1334]
## Overview

In order, to solve this security issue: https://github.com/kubeshop/botkube/security/dependabot/21, we need to update keptn plugin deps. At the time of writing this issue (18.12.23) it is still not fixed on the upstream: https://github.com/keptn/go-utils/blob/master/go.mod#L16

## Acceptance Criteria

- [ ] Double check if we don't use the code with the security issue, related to the otel pkg
- [ ] Test e2e that keptn plugin is still working properly

**Comment by pkosiec** [comment]
The affected code isn't used by our plugin, so closing the issue.
