### ISSUE TITLE
Notification not working

### ISSUE THREAD

**Issue by malikal-hh** [kubeshop/botkube#1368]
## Expected behavior

Notification working

## Actual behavior

Notification not working

## Steps to reproduce

#!/bin/bash
export SLACK_API_APP_TOKEN="xxx"
export SLACK_API_BOT_TOKEN="xxx"
export CLUSTER_NAME="xxx"
export ALLOW_KUBECTL=true
export ALLOW_HELM=true
export SLACK_CHANNEL_NAME="botkube"

botkube install --version v1.7.0 \
--set communications.default-group.socketSlack.enabled=true \
--set communications.default-group.socketSlack.channels.default.name=${SLACK_CHANNEL_NAME} \
--set communications.default-group.socketSlack.appToken=${SLACK_API_APP_TOKEN} \
--set communications.default-group.socketSlack.botToken=${SLACK_API_BOT_TOKEN} \
--set settings.clusterName=${CLUSTER_NAME} \
--set 'executors.k8s-default-tools.botkube/kubectl.enabled'=${ALLOW_KUBECTL} \
--set 'executors.k8s-default-tools.botkube/helm.enabled'=${ALLOW_HELM} \
--set settings.log.level="debug"

**Comment by pkosiec** [comment]
Hi @malikal-hh, 
I'm sorry, but we would need some details to help you. Could you describe specifically which notifications don't work for you? What do you exactly expect to see? 
- What Kubernetes resources you'd like to receive notifications about?
- Which Kubernetes manifests you used to check if the notifications are triggered? 
- Have you followed the [Basic diagnostics](https://docs.botkube.io/operation/diagnostics) document to see if Botkube is operating properly? Anything in the logs?
Please provide us a way to reproduce your issue. Thanks!

**Comment by pkosiec** [comment]
Closing as we would need a bit more info. Feel free to ping me with additional details and I'll reopen the issue. Cheers!
