### ISSUE TITLE
Helm plugin missing from plugins-index.yaml for 1.9.0

### ISSUE THREAD

**Issue by rocket357** [kubeshop/botkube#1399]
## Description

Comparison of plugins-index.yaml for 1.8.0 vs 1.9.0 shows the following:

jon@host:~/git/botkube$ yq .entries[].name ../plugins-index-1.8.0.yaml
"exec"
"helm"
"kubernetes"
"argocd"
"github-events"
"keptn"
"prometheus"
"doctor"
"flux"
"kubectl"

jon@host:~/git/botkube$ yq .entries[].name ../plugins-index-1.9.0.yaml
"kubectl"
"kubernetes"

It doesn't appear that [hack/gen-plugin-index.go](https://github.com/kubeshop/botkube/blob/main/hack/gen-plugin-index.go) changed, so I'm not sure why these are so vastly different, nor could I find any changelog that explicitly stated those sources/executors would be disabled (possible I overlooked something, though that's a fairly large list of removed plugins?).

## Expected behavior

helm executor would continue to work with 1.9.0 upgrade.

## Actual behavior

upgrade fails with the following logged:

{"component":"Plugin Manager","forceUpdate":true,"level":"info","msg":"Downloading repository index","repo":"botkube","time":"2024-02-26T18:03:11Z","url":"https://github.com/kubeshop/botkube/releases/download/v1.9.0/plugins-index.yaml"}
{"component":"Health server","level":"info","msg":"Shutdown requested. Finishing...","time":"2024-02-26T18:03:11Z"}
{"component":"Analytics reporter","level":"info","msg":"Closing...","time":"2024-02-26T18:03:11Z"}
{"level":"fatal","msg":"while running application: while waiting for goroutines to finish gracefully: 1 error occurred:\n\t* while starting plugins manager: not found executor plugin called \"helm\" in \"botkube\" repository","time":"2024-02-26T18:03:12Z"}

## Steps to reproduce

Upgrade 1.8.0 to 1.9.0 with helm executor enabled.

**Comment by brampling** [comment]
Botkube is introducing new plugins with advanced functionality that will be part of the Botkube Team and Enterprise packages. These advanced plugins require cloud services provided by Botkube and are not part of the Botkube open source software.

As part of this change, some of the existing Botkube plugins are being moved to a new repository. This repository requires authentication with a Botkube account. To continue using these Botkube plugins, create an account at https://app.botkube.io/ and configure a Botkube instance, or [migrate an existing installation with the Botkube CLI](https://docs.botkube.io/cli/migrating-installation-to-botkube-cloud).

**Comment by rocket357** [comment]
So the botkube plugins are no longer usable self-hosted?  Thanks for the clarification.

`jon@host:~$ ./botkube uninstall
Uninstalling botkube Helm release...
 • Release details:

      Release Name          botkube
      Namespace             botkube
      Kubernetes Context    kubernetes-admin@kubernetes

 ? Do you want to delete existing installation? Yes
 ✓ Uninstalling... [took 6s]`

Thanks!
