### ISSUE TITLE
Replace discontinued `files.upload` API in Slack platforms

### ISSUE THREAD

**Issue by mszostok** [kubeshop/botkube#1438]
## Overview

The [files.upload web API method](https://api.slack.com/methods/files.upload) that we use to upload a long messages (e.g. logs) will be discontinued. 

> To prepare for this change, we recommend migrating away from files.upload and instead using the combination of [files.getUploadURLExternal](https://api.slack.com/methods/files.getUploadURLExternal) and [files.completeUploadExternal](https://api.slack.com/methods/files.completeUploadExternal). More information on how to use these two APIs together can be found on our [Uploading files documentation](https://api.slack.com/messaging/files#uploading_files). You can also leverage Slack’s SDKs to help you transition to this new way of uploading files by visiting our [api.slack page](https://api.slack.com/messaging/files#uploading_files).

## Acceptance Criteria

- [ ] Update Slack platforms to use new API
- Probably we need to contribute/fork/extend the library:
   - https://github.com/slack-go/slack/issues/1288
   - https://github.com/slack-go/slack/issues/1287

## Reason

Support for the `files.upload` API will be discontinued on **March 11, 2025.**

**Comment by mszostok** [comment]
The issue is more critical than we thought initially. The cloud version of our application will work fine until sunset on **March 11, 2025**.

However, all new applications created after **May 16, 2024** are no longer able to use this API method. **This means that our Socket Slack lacks the file upload feature for all new users since May 16, 2024.**

![image](https://github.com/kubeshop/botkube/assets/17568639/1a63c850-55d1-498e-9267-a0792745e2c0)

cc @brampling

**Comment by vaijab** [comment]
This is currently blocked / parked until either Slack fixes their API or we're forced to require `files:read` permissions scope for our bot app.

See [this slack thread](https://kubeshop.slack.com/archives/C06GQEJJAG0/p1720616832123569?thread_ts=1720099512.276069&cid=C06GQEJJAG0) for more details about the issue with Slack API.

**Comment by lorenzoaiello** [comment]
@vaijab , what is the problem with the slack API? There shouldn't be any permission scope changes required to transition to the new API endpoints.
