### ISSUE TITLE
Panic: Send on Closed Channel in Slack SocketMode Client

### ISSUE THREAD

**Issue by maks3201** [kubeshop/botkube#1475]
# Bug Report: Panic - Send on Closed Channel in Slack SocketMode Client

## Description

The Botkube application encounters a panic with the message `send on closed channel` when running the Slack SocketMode client. This issue appears to occur in the `receiveMessagesInto` method within `slack-go/slack` version `v0.12.2`. The issue happens intermittently during the message reception process, causing Botkube to restart unexpectedly. This behavior was observed on Botkube version `v1.8.0`, deployed via Helm.

## Expected behavior

The Slack SocketMode client should handle messages without triggering a panic, even if channels are closed.

## Actual behavior

Botkube panics with a `send on closed channel` error, disrupting the Slack integration and triggering an automatic restart. This seems to happen during the message reception phase, as indicated in the logs.

## Steps to reproduce

1. Set up Botkube version `v1.8.0` with Slack integration using SocketMode, deployed via Helm.
2. Start Botkube and allow it to receive messages for an extended period.
3. Observe intermittent panics with the message `send on closed channel`, followed by a restart of the Botkube process.

## Logs

```
panic: send on closed channel

goroutine 112834 [running]:
github.com/slack-go/slack/socketmode.(*Client).receiveMessagesInto(0xc00097ee10, {0x2dc2430, 0xc0000baaf0}, 0xc000b2c180?, 0xc000bb0120)
    /home/runner/go/pkg/mod/github.com/slack-go/slack@v0.12.2/socketmode/socket_mode_managed_conn.go:471 +0x225
github.com/slack-go/slack/socketmode.(*Client).runMessageReceiver(...)
    /home/runner/go/pkg/mod/github.com/slack-go/slack@v0.12.2/socketmode/socket_mode_managed_conn.go:362
github.com/slack-go/slack/socketmode.(*Client).run.func4()
    /home/runner/go/pkg/mod/github.com/slack-go/slack@v0.12.2/socketmode/socket_mode_managed_conn.go:132 +0x9a
created by github.com/slack-go/slack/socketmode.(*Client).run in goroutine 167
    /home/runner/go/pkg/mod/github.com/slack-go/slack@v0.12.2/socketmode/socket_mode_managed_conn.go:127 +0x6a5
```

---

Please advise on potential fixes or workarounds, and if any updates are available to address this issue.

**Comment by pkosiec** [comment]
Hi @maks3201, please try to use the latest version (1.13) as I believe we fixed the issue in one of the newer releases 👍
