### ISSUE TITLE
Running kubectl command out of order

### ISSUE THREAD

**Issue by daegeun-ha** [kubeshop/botkube#208]
**Is your feature request related to a problem? Please describe.**
When I type 'get pod -n monitoring' it works well.
But when I type like '-n monitoring get pod', although it is right syntax of kubectl command, botkube determines it is not available command.
It is because before run some kubectl commands, it watch the first argument and determine whether it is included in 'validKubectlCommands' or not. I think it is little bit strict.

**Describe the solution you'd like**
How about optionize it. (like in values.yaml)
If user wants to filter kubectl commands, algorithm runs same as current version.
But if user doesn't want to filter kubectl command and wants to use kubectl command freely,  run kubectlcommand without validation at the end of Execute() method. And kubernetes api server will determine it is right command or not.

**Describe alternatives you've considered**

**Additional context**

**Comment by Omkar0114** [comment]
Hi @PrasadG193 I want to work on this issue, Can anyone assign it to me?

**Comment by Omkar0114** [comment]
Hey @pkosiec I just ran both commands which describes this issue. 
`@Botkube k get pods -n dev` It works fine. 
`@Botkube k -n dev get pods` It also works fine. 

Is this feature added? This issue was opened a long time ago!!

![Screenshot from 2023-09-01 12-01-21](https://github.com/kubeshop/botkube/assets/88308267/2018c4e1-8a42-4f78-92e5-cd2b83b9f01d)

**Comment by pkosiec** [comment]
Hi @Omkar0114,
Thank you for checking that. That's correct, kubectl plugin was rewritten a while ago and now it supports different param order 🙂 Looks like we forgot to close this issue.
Thank you again for your help!
