### ISSUE TITLE
Automated Pod debugging

### ISSUE THREAD

**Issue by timstoop** [kubeshop/botkube#231]
**Is your feature request related to a problem? Please describe.**
When a Pod restarts, it still requires some manual steps to figure out *why* it restarted. Those steps could actually be automated, as almost all of that information is part of the Pod status. It would be nice if instead of just notifying you that a Pod has restarted (which Prometheus already does as well), botkube would perform a few automated tests to determine more information about it.

**Describe the solution you'd like**
A very simple solution to start out with would be:

Pod restarts -> Check the status of the container that caused the restart -> Is it OOMKilled? report that -> Is it Terminated with non-zero exit status? Report that and maybe show the last 100 lines of the previous log for the Pod

Afterwards, this could be extended with a form of knowledge base. For instance, if the exit code is 137, it could inform that this often happens when the application itself determines that it does not have enough memory available and kills itself with a sigkill. This would make it a lot easier for especially new Kubernetes users to start debugging their apps on Kubernetes.

**Describe alternatives you've considered**
We've currently documented these steps for our users. Having them automated would be preferred.

**Comment by pkosiec** [comment]
Closing as it is already possible with actions (automations) and custom executor plugins 🙂 See docs:
- https://docs.botkube.io/configuration/action
- https://docs.botkube.io/plugin/custom-executor

If you're missing anything from these features, please create a separate issue. Thanks!
