### ISSUE TITLE
Load filters dynamically using go plugin

### ISSUE THREAD

**Issue by PrasadG193** [kubeshop/botkube#24]

**Comment by PrasadG193** [comment]
Initial proposal document: https://github.com/PrasadG193/botkube/blob/filters-goplugin/design/dynamic-filters-loading.md

Open questions:
- Should we use volumes to store downloaded plugins?
- We can have a dedicated GitHub repo (like botkube-filters) which will contain standard plugins. And we can include these plugins as defaults in BotKube docker image. Any thoughts?

cc: @ssudake21

**Comment by pkosiec** [comment]
Thanks for the proposal! This will be continued as a part of https://github.com/kubeshop/botkube/issues/657
