### ISSUE TITLE
[CD] Add a continuous deployment Job

### ISSUE THREAD

**Issue by PrasadG193** [kubeshop/botkube#247]
**Is your feature request related to a problem? Please describe.**

We should have a CD job to deploy and validate BotKube artifacts - helm charts and all-in-one resource manifests

**Describe the solution you'd like**
Ideally, we should have 2 BotKube instances -
- One pointing to the latest commit in develop
- Another one to the latest release 

Edit:
We have applied for free AWS credits under their Open source program.
Till we get that, we can use Kind to deploy and validate the deployments

**Comment by mbtamuli** [comment]
We can enable GitHub Pages to enable the all-in-one resource manifest downloads.
Similar to https://docs.litmuschaos.io/docs/next/getstarted.html#install-litmus

**Comment by mbtamuli** [comment]
Also check https://github.com/actions/upload-release-asset

**Comment by baba230896** [comment]
Hi @PrasadG193 
Picking up this task.

**Comment by pkosiec** [comment]
Hi, I'm closing this as current CI pipeline already installs BotKube via Helm chart on local k3d cluster, and we probably won't have long-running cluster anytime soon. Cheers!
