### ISSUE TITLE
Customise RBAC using the resource_config.yaml, and add only essential resources authorisation

### ISSUE THREAD

**Issue by rahulchheda** [kubeshop/botkube#254]
**Is your feature request related to a problem? Please describe.**
This issue addresses the creation of dynamic RBAC, which means when we run the binary, we create a RBAC, and then ask the user to apply that RBAC yaml, and provide limited authorization to botkube.
I think that would be a great module in your recommendation engine.

**Describe the solution you'd like**
We start with a [*,*,*] RBAC auth, but soon we ping a message in Slack, or any other medium to reduce the authorization if the RBAC.
We analyze the resource_config.yaml, and then create an RBAC, and present it to the user, this might help in the case of CR's that the user is trying to get but the static RBAC is unable to access those.

**Describe alternatives you've considered**

**Additional context**

**Comment by PrasadG193** [comment]
@rahulchheda Can you please more description to the issue? Also please check if https://github.com/infracloudio/botkube/pull/255 addresses this

**Comment by rahulchheda** [comment]
This issue addresses the creation of dynamic RBAC, which means when we run the binary, we create a RBAC, and then ask the user to apply that RBAC yaml, and provide limited authorisation to botkube.

**Comment by rahulchheda** [comment]
We analyze the resource_config.yaml, and then create an RBAC, and present it to the user, this might help in the case of CR's that the users is trying to get but the static RBAC is unable to access those.

**Comment by rahulchheda** [comment]
Does that make sense? @PrasadG193

**Comment by PrasadG193** [comment]
Ok. RBAC at BotKube level will be complicated. Could you please put this info in issue's description?
https://github.com/infracloudio/botkube/issues/254#issue-599407305

**Comment by rahulchheda** [comment]
Sure, but why is it complicated, we have the resources, we have the actions for what we have to watch. Could you explain why it seems complicated?

**Comment by PrasadG193** [comment]
Aah, I misread your comment. I was thinking configuring K8s RBAC for Slack/Mattermost user. But having dynamic RBAC based on configuration sounds great.

**Comment by pkosiec** [comment]
Hi,
Please check out the latest Botkube which comes with RBAC configuration: https://docs.botkube.io/configuration/rbac
If there's anything missing, please create a new issue. Cheers!
