### ISSUE TITLE
[Refactor] Refactor notifier to use Bot interface to send events

### ISSUE THREAD

**Issue by PrasadG193** [kubeshop/botkube#270]
**Is your feature request related to a problem? Please describe.**

In notifier, we send events by creating new connection to communication medium on every new event. We can reduce number of connections by sending messages via Bot interface. 

**Describe the solution you'd like**

Implement required methods in Bot interface so that it satisfies Notifier interface. Then add Bot object as a notifier in main function

**Comment by codenio** [comment]
TODO:
- pass config from main.py instead of creating config from the file in all the bots .
https://github.com/infracloudio/botkube/blob/7aaf5112c611e78ef8b89c9e70b1a4356cc400ed/pkg/bot/slack.go#L54-L59

**Comment by codenio** [comment]
> In notifier, we send events by creating a new connection to communication medium on every new event.

@PrasadG193 at present, creating a new connection on each event using goroutines, prevents the accumulation of event notifications.  I have few thoughts with this

- would a single connection using the bot interface slow down/choke the event notifications sent to the servers?
- can we reduce the number of connections by queuing the even notifications and serve them with a fixed number of workers?

**Comment by PrasadG193** [comment]
I agree. Eventually, we would need to have queuing mechanism. We are also adding audit webhook support, which again increases the number of events BotKube needs to process. We are thinking about refactoring architecture so work on high load.
