### ISSUE TITLE
Segregate botkube commands in processors

### ISSUE THREAD

**Issue by sanketsudake** [kubeshop/botkube#28]
Currently, we have two types of commands,

1. Botkube commands - commands which are botkube specific
2. Kubectl commands - kubectl commands which are executed on kubernetes cluster

We have a single parser code which is executing botkube commands. We can breakdown this code into processors so that we can easily add new commands in botkube commands set.

Basically something similar to filter engine for recommendations.

**Comment by pkosiec** [comment]
Hi, the executors were already refactored as a part of https://github.com/kubeshop/botkube/issues/596, so that means the task has been resolved. We will also go a few steps further in the #650 epic. Cheers!
