### ISSUE TITLE
Ability to customize Bot Image and Name Similar to Travis-CI for example

### ISSUE THREAD

**Issue by DMSecureYourInbox** [kubeshop/botkube#280]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The ability to upload an image for the bot and also change the name of the bot. An example application that allow this is Travis-CI

**Describe alternatives you've considered**
N/A

**Additional context**
The ability to personalize this would be awesome!

**Comment by pkosiec** [comment]
Closing as completed, as currently you can configure any bot name and image for each communication platform we support 🙂 For example, see https://docs.botkube.io/installation/slack/.
