### ISSUE TITLE
Shorter commands in BotKube

### ISSUE THREAD

**Issue by vishal-biyani** [kubeshop/botkube#294]
The Kubectl commands tend to get pretty long on BotKube and there is no auto-completion that does not help. What would be nice is to have a way to use [Kubectl aliases](https://github.com/ahmetb/kubectl-aliases) or something similar - so the length of that overall command reduces

**Comment by gmkumar2005** [comment]
Hi @vishal-biyani can this be done in a way that it does not impact the channel and also does not impact the executor. 
Each channel may need to use different style of encoding/translation. For example Telegram does not process commands with a hyphen so I had to translate an underscore to hyphen before executing. Each channel will have their own corner cases. 
It will be nice if this feature works like a plugin and channel should be able to enhance or opt-out.

**Comment by mszostok** [comment]
This issue will be solved by https://github.com/kubeshop/botkube/issues/870
