### ISSUE TITLE
Add integration tests for DiscordApp

### ISSUE THREAD

**Issue by codenio** [kubeshop/botkube#307]
## Description

Add integration tests for Discord.

## Acceptance criteria
- setup a real Discord workspace in the same way as we did for Slack
- extend the e2e integration test framework, so it supports Discord 
  - it should be extensible for the future where we will add e.g. Mattermost, MS Teams etc
  - consider to use interfaces that different drivers can implement
- update the e2e test pipeline to run the test
  - consider running it in parallel

**Comment by pkosiec** [comment]
Hey @ezodude,

> This is different from using the Bot to listen to messages - which most examples explain.

I've just took a quick look now, and it should be fairly easy to get messages synchronously, with:

```go
	channel, err := api.Channel("channelID")
	// see the channel.Messages property
```

More: https://discord.com/developers/docs/resources/channel#get-channel-message

> It looks there might be some Guild setup that to create channels.

And yes, you'd need to create a Guild (https://discord.com/developers/docs/resources/guild#create-guild) and then channel (https://discord.com/developers/docs/resources/guild#create-guild-channel) - the `discordgo` has very similarly organized methods as the REST API, that's why I'm linking to the official dev docs.

Let me know if you need any help 👍

**Comment by ezodude** [comment]
@pkosiec Appreciate the comments. To confirm, I am also using the REST API docs to work with Discord.

> I've just took a quick look now, and it should be fairly easy to get messages synchronously, ...

Didn't see that one, thank you.

It's the Guilds that I was looking to understand. The documentation states:

> Guilds in Discord represent an isolated collection of users and channels, and are often referred to as "servers" in the UI.

I already have a BotKube E2E Server or "Guild" with `BotKube` and the `BotKube-Tester` already setup.
- I'm trying to understand if I'll need to use that Guild's ID.
- Or I really have to create a new Guild ... and ... (not sure how the Bots can be added)

No blockers here. Just a bit of doc reading and some trial and error.

**Comment by ezodude** [comment]
Almost done - [here's a draft PR](https://github.com/kubeshop/botkube/pull/723) of work so far.

## Pending

- [ ]  Minor redesign to make the tests extensible for the future (e.g. MatterMost, etc..)
- [ ]  Updated docs to explain how to setup a discord server for local runs.
- [ ]  Setup a real Discord Guild/Server in the same way we have for Slack.
- [ ]  Updating the PR GitHub action for discord.

**Comment by ezodude** [comment]
Reminder: add follow ticket to re-include colours in e2e tests using an abstracted collar model.

For example, like the following:
```go
type Color int

const (
	Red Color = iota
	Yellow
	Green
)

// used in slack driver
func ToSlack(in Color) string {
	switch in {
	case Green:
		return "#..."
	case Yellow:
		return "#..."
	case Red:
		return "#..."
	default:
		return ""
	}
}

// used in discord driver
func ToDiscord(in Color) int {
	switch in {
	case Green:
		return 123
	case Yellow:
		return 123
	case Red:
		return 123
	default:
		return 0
	}
}
```

**Comment by ezodude** [comment]
> consider running it in parallel

BTW, not sure how to enable this using helm test? Open to ideas.

**Comment by mszostok** [comment]
Hi @ezodude 

I see a couple of options.
1. Skip using `helm test` and just run `make test-integration-discord` and `make test-integration-slack` with proper envs
2. Define two testing Pods (currently we have only [one](https://github.com/kubeshop/botkube/blob/main/helm/botkube/templates/tests/e2e-test.yaml#L1)). One pod names `test-slack` and the second `test-discord`. One will run only slack and second discord tests via changed container CMD.
  There is a `helm test {foo} --filter "name={pod_name}"` command, so you can run later on CI two jobs:
  1. `helm test botkube --namespace botkube --timeout=$INTEGRATION_TESTS_TIMEOUT --logs --filter "name=test-discord"`
  2.   `helm test botkube --namespace botkube --timeout=$INTEGRATION_TESTS_TIMEOUT --logs --filter "name=test-slack"`
  

Here is an example `foo` Helm chart to demo that: [foo.zip](https://github.com/kubeshop/botkube/files/9586455/foo.zip)

1. Install: `helm install foo ./foo`
2. Test all: `helm test foo`
3. Run only test-connection Pod: `helm test foo --filter "name=test-connection"`
4. Run only test-other Pod: `helm test foo --filter "name=test-other`
