### ISSUE TITLE
Add queuing mechanism to process events

### ISSUE THREAD

**Issue by PrasadG193** [kubeshop/botkube#310]
**Is your feature request related to a problem? Please describe.**

We send events to filterengine and notifiers as soon as those occur. This won't work in case of a high load. We should have a better mechanism to work efficiently under high load.

**Describe the solution you'd like**

We can maintain buffer or queue.

**Comment by pkosiec** [comment]
Hey, I think currently it's very rare to have so many channels configured that we'll hit some performance issues. There wasn't any issue from the community, so let's revisit that in future if community requests such improvement. Cheers!
