### ISSUE TITLE
Errors spamming logs when using a service account with limited access to resources

### ISSUE THREAD

**Issue by adusumillipraveen** [kubeshop/botkube#318]
**Describe the bug**
We are using service account with limited access to resources as we don't want to expose all resources through kubectl.

see config : https://github.com/hmcts/cnp-flux-config/blob/master/k8s/namespaces/monitoring/botkube/botkube.yaml#L125-L136

But it spams logs with errors though works functionally. It would good to use these settings while fetching resources instead of fetching all of them.
https://github.com/hmcts/cnp-flux-config/blob/master/k8s/namespaces/monitoring/botkube/botkube.yaml#L28

**To Reproduce**
1. Add a ServiceAccount with limited access to resources which need to be accessed from kubectl.
2. This causes errors to be spammed through out in logs

**Expected behavior**
Give a control on what should be allowed in kubectl and what should be allowed to be monitored by botkube so that the lists will be configured separately and user has control over rbac.

**Screenshots**
NA
**Additional context**
NA

**Comment by PrasadG193** [comment]
Fixed with https://github.com/infracloudio/botkube/pull/253

**Comment by PrasadG193** [comment]
My assumption was dynamic client will address this, but this is not the case.
We should check if BotKube SA has permission to LIST resources configured with [`SelfSubjectAccessReview`](https://godoc.org/k8s.io/kubernetes/pkg/apis/authorization#SelfSubjectAccessReview) API before creating informers.

**Comment by pkosiec** [comment]
Hey @adusumillipraveen Please try the latest Botkube 1.0.1 and see if the error still occurs. If yes, feel free to reopen/recreate the issue. Thanks!
