### ISSUE TITLE
Getting Blank Notification over Msteam

### ISSUE THREAD

**Issue by vinamra1502** [kubeshop/botkube#321]
helm install --version v0.10.0 --name botkube --namespace botkube  --set communications.webhook.enabled=true   --set communications.webhook.url=******   --set config.settings.clustername=TV-DEV-K8s   --set image.repository=infracloudio/botkube   --set image.tag=v0.10.0
 infracloudio/botkube -f values.yml
I am using msteam channel Webhook url but getting blank notification.
![image](https://user-images.githubusercontent.com/13641170/89636028-99e06b80-d8c5-11ea-939b-3d406b74cfea.png)

**Comment by pkosiec** [comment]
Hi, 

the only way to integrate with MS Teams is to use the official integration. Here's the tutorial how to configure it: https://botkube.io/installation/teams/

Cheers!
