### ISSUE TITLE
Notify groups

### ISSUE THREAD

**Issue by mikebell90** [kubeshop/botkube#323]
**Is your feature request related to a problem? Please describe.**
It would be awesome to be able to apply "notify groups". Yes annotations help, but it would cool to apply notify groups for particular objects. For example only the system group needs to hear about kuberhealthy or kube-system stuff. We could laboriously TRY to apply annotations to redirect these, but notify groups would be awesome

**Comment by codenio** [comment]
This feature is currently available for slack channels, using annotations `botkube.io/channel: <channel_name>`

Annotation ```botkube.io/channel: <channel_name>``` sends events notifications of the annotated object to the mentioned channel.

If this satisfies your requirement, kindly close this issue

**Comment by mikebell90** [comment]
That's not remotely practical in most cases, as noted above.

**Comment by vishal-biyani** [comment]
Hi @mikebell90 Can you please elaborate on what do you mean by "notify groups"?

**Comment by mikebell90** [comment]
To apply matches to every single possible notifier rule. These matcheers are "groups"

**Comment by pkosiec** [comment]
Closing as it was implemented as a part of https://github.com/kubeshop/botkube/issues/596. With the new configuraton you can fine-tune the notifications for multiple channels. Stay tuned for final 0.13!

When it comes to the annotations feature, here's an aggregated task you can subscribe to to follow the progress: https://github.com/kubeshop/botkube/issues/690. Feel free to comment it if you see something missing from the scope.

Cheers!
