### ISSUE TITLE
prometheus integration to grab snapshots of metrics

### ISSUE THREAD

**Issue by mikebell90** [kubeshop/botkube#324]
This would be SUPER awesome

@BotKube prometheus query="xxxxxx" output=picture|table interval="now-3h to now"

That's not great syntax but you get the idea

**Comment by PrasadG193** [comment]
Need to add new BotKube command. BotKube command execution implementation is here: https://github.com/infracloudio/botkube/blob/develop/pkg/execute/executor.go#L180

**Comment by christyjacob4** [comment]
@PrasadG193 What would be the scope of this task ?

**Comment by PrasadG193** [comment]
Hey @mikebell90, could you please add more details like - Which Prometheus you are talking about (deployed in cluster or external)? We will also need to find a way to configure Prometheus endpoint

**Comment by pkosiec** [comment]
Hey, Prometheus integration is already there for a few months already. Here are the docs: https://docs.botkube.io/configuration/source/prometheus

If you're missing any feature in it, please create a new issue. Thanks!
