### ISSUE TITLE
Add test coverage for '@BotKube notifier showconfig` command

### ISSUE THREAD

**Issue by PrasadG193** [kubeshop/botkube#349]
**Is your feature request related to a problem? Please describe.**

Test coverage is missing for notifier commands

**Describe the solution you'd like**

`@BotKube notifier showconfig` displays resource configuration that BotKube monitors and notifies about. See https://www.botkube.io/usage/#view-botkube-configuration

Integration tests for validating BotKube command responses are implemented here: https://github.com/infracloudio/botkube/blob/develop/test/e2e/command/botkube.go#L46

Add test case to validate  `@BotKube notifier showconfig` command in the existing table drive test cases

**Comment by anoopmsivadas** [comment]
@PrasadG193  can I work on this issue?

**Comment by PrasadG193** [comment]
Go for it @anoopmsivadas. Please let me know if you have any doubts.

**Comment by anoopmsivadas** [comment]
@PrasadG193 Hi, I tried running the tests before changing anything and it failed.Did it on my local machine. Here is the output.

```ok  	github.com/infracloudio/botkube/pkg/filterengine/filters	(cached)
?   	github.com/infracloudio/botkube/pkg/log	[no test files]
?   	github.com/infracloudio/botkube/pkg/metrics	[no test files]
# github.com/infracloudio/botkube/pkg/notify
pkg/notify/webhook.go:130:50: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
pkg/notify/webhook_test.go:41:44: conversion from untyped int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
FAIL	github.com/infracloudio/botkube/pkg/notify [build failed]
FAIL
```

**Comment by anoopmsivadas** [comment]
hi @PrasadG193 , I'm facing issues while testing.This happens everytime i run the test on my local machine. I tried without making any changes
```PASS
ok  	github.com/infracloudio/botkube/pkg/filterengine/filters	(cached)
?   	github.com/infracloudio/botkube/pkg/log	[no test files]
?   	github.com/infracloudio/botkube/pkg/metrics	[no test files]
# github.com/infracloudio/botkube/pkg/notify
pkg/notify/webhook.go:130:50: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
pkg/notify/webhook_test.go:41:44: conversion from untyped int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
FAIL	github.com/infracloudio/botkube/pkg/notify [build failed]
FAIL
```

**Comment by PrasadG193** [comment]
@anoopmsivadas We use Go 1.13 in CI (https://github.com/infracloudio/botkube/blob/develop/.github/workflows/ci.yml#L18). Can you please try once with 1.13?

**Comment by anoopmsivadas** [comment]
@PrasadG193  that issue is resolved.  but it seems to skip some tests due to LF character. I checked some CI logs of previously merged PRs and the same error is there 

```=== RUN   TestRun/command/Test_Kubectl_command/BotKube_get_pods_out_of_configured_channel
INFO[2020-09-29T11:33:01+05:30] Invalid request. Dumping the response        
=== RUN   TestRun/command/Test_Kubectl_command/BotKube_get_pods_from_configured_channel
ERRO[2020-09-29T11:33:02+05:30] Error in sending message:invalid character '\n' in string literal 
=== RUN   TestRun/command/Test_BotKube_command
=== RUN   TestRun/command/Test_BotKube_command/BotKube_filters_list
ERRO[2020-09-29T11:33:03+05:30] Error in sending message:invalid character '\n' in string literal 
=== RUN   TestRun/command/Test_BotKube_command/BotKube_commands_list
ERRO[2020-09-29T11:33:04+05:30] Error in sending message:invalid character '\n' in string literal 
=== RUN   TestRun/command/Test_BotKube_command/BotKube_ping
ERRO[2020-09-29T11:33:05+05:30] Error in sending message:invalid character '\n' in string literal 
``````

**Comment by pkosiec** [comment]
Hi, closing this issue as we'll add the tests once we rework the commands to unify its naming (hopefully soon) - https://github.com/kubeshop/botkube/issues/703. Cheers!
