### ISSUE TITLE
botkube help command

### ISSUE THREAD

**Issue by codenio** [kubeshop/botkube#393]
**Is your feature request related to a problem? Please describe.**
Need to add `@botkube help` command in addition to `/botkubehelp` as custom commands are not supported by all platforms (discord for example) 

**Describe the solution you'd like**
add  `@botkube help` command to the command list

**Comment by PrasadG193** [comment]
@codenio we had thought about this but this will return a duplicate response for multiple cluster env.

**Comment by mszostok** [comment]
Will be handled in https://github.com/kubeshop/botkube/issues/683
