### ISSUE TITLE
add support for default cluster and namespace on any Slack channels

### ISSUE THREAD

**Issue by sgandon** [kubeshop/botkube#421]
### **Is your feature request related to a problem? Please describe.**
When inviting @botkube on any channel or using it in @botkube DM,
If you want to issue a series of kubectl command on a cluster it is really annoying to have to specify the cluster name or the namespace all the time.
 

### **Describe the solution you'd like**
It would be nice to have the same behaviour as one expect from the kubectl command line that is having a default cluster and namespace.
I would suggest to add a couple of commands :
```
1/   @botkube cluster [<name of the default cluster>]
2/   @botkube namespace [<name of the default namespace>]
```
1/ the first command would set the default cluster when specified or display the default cluster if name is empty
2/ the second command would set the default namespace when specified or display the default namespace if name is empty

This would be refused for channels that are linked to a cluster using the configuration yaml file.

### **Additional context**
In terms of implementation (if ever possible) this would mean the default cluster that is set would be the only one to respond to this channel when `--cluster-name` is not used.
It would have to store the channel name in order to know if it can answer or not. The default namespace should be stored along with the channel name and used when the backend chooses to respond.
This storage could be done in-memory (for simple implem) but this would mean to loose those settings if the backend pod restarts or it could be persisted (PV or ConfigMap).

**Comment by sgandon** [comment]
I am working on it

**Comment by pkosiec** [comment]
Hi @sgandon,

With the upcoming BotKube 0.13 you'll be able to configure default namespace per a given Executor config. You can have multiple executor configurations, and you can bind them to specific channels. You can also set up different execution configurations for multiple BotKube installations. Please take a look at the documentation: https://botkube.io/configuration/executor/

If you'd like to avoid using `--cluster-name` flag when having multiple BotKube installation bound to a single channel, then the current workaround is to have multiple channels with a single specific cluster assigned. We would like to keep the current behavior (respond when no `--cluster-name` flag is not specified). IMHO such channels separation could make sense in most scenarios (e.g. have separate `dev` / `stage` / `prod` channels for each cluster).

I assume with such `@BotKube cluster set {name}` command you suggested we would need to tell all BotKube installations to check, if a given installation has the `clusterName` posted in the message to bot, and if not, then silent all future commands execution. If that was saved in-memory, then on every restart the config would be lost. That doesn't sound as a “bulletproof” solution to me, so we would need to come up with something more sophisticated.

Of course, we are open for discussing it further, and we'll definitely consider implementation depending on the community demand 🙂 Let me know what do you think!
