### ISSUE TITLE
Helm commands

### ISSUE THREAD

**Issue by theminecoder** [kubeshop/botkube#433]
**Is your feature request related to a problem? Please describe.**
Be able to use helm commands from the bot to install/upgrade charts while on the go.

**Describe the solution you'd like**
Just like we can run kubectl, we would be able to run helm commands with support for `--cluster-name`. 

**Describe alternatives you've considered**

**Additional context**

**Comment by pkosiec** [comment]
Resolved by https://github.com/kubeshop/botkube/issues/843 in 0.17 🙂
