### ISSUE TITLE
Add e2e test for namespace checker filter

### ISSUE THREAD

**Issue by PrasadG193** [kubeshop/botkube#443]
**Is your feature request related to a problem? Please describe.**

Add an e2e test to verify namespace checker filter https://github.com/infracloudio/botkube/blob/develop/test/e2e/filters/filters.go#L44

**Additional context**

This is a followup task of https://github.com/infracloudio/botkube/pull/437

**Comment by pkosiec** [comment]
Thank you, this functionality now is covered under E2E tests. I'm closing it as resolved.
Here's the aggregated epic with future test improvements: https://github.com/kubeshop/botkube/issues/589
