### ISSUE TITLE
Support using multiple Slack channels with different configuration

### ISSUE THREAD

**Issue by doronmak** [kubeshop/botkube#444]
I didn't see an option to use the same bot instance for a different configuration.
for example, I want to create a channel for an error of pods and another channel for node problems.
I think it can be really useful.
maybe can be a configuration per channel and you can manage your channel and your message needed in the same place.

thank you a lot.

**Comment by lemaral** [comment]
I would like also to use different channels for separate namespaces, to allow developers to monitor only their related workloads instead of having to watch everything

**Comment by PrasadG193** [comment]
We had started with the profiling feature https://github.com/infracloudio/botkube/pull/291 which makes it possible to have a more fined-grained BotKube configuration. But that needs some rework to be done

**Comment by bygui86** [comment]
hi guys, what's the status of this feature? it would be really really useful :)

**Comment by pkosiec** [comment]
Closing as it was implemented in https://github.com/kubeshop/botkube/issues/596. BotKube 0.13 is just around the corner, stay tuned!
