### ISSUE TITLE
Filter events by event.reason

### ISSUE THREAD

**Issue by trntv** [kubeshop/botkube#478]
**Is your feature request related to a problem? Please describe.**
We want to receive notifications about all errors/warning except FailedScheduling as it is a normal state and it triggers cluster autoscaling. With cluster built mostly on spot instances it happens often

**Describe the solution you'd like**
It would be nice to have a built-in filter on `reason`

**Describe alternatives you've considered**
I wrote custom filter but it would be nice to have built-in filter.

**Comment by ezodude** [comment]
Closing this.

To avoid duplication, please [see comments on the proposed PR](https://github.com/kubeshop/botkube/pull/479#issuecomment-1232988813).
