### ISSUE TITLE
[FR] Improve resources configuration in Helm Chart

### ISSUE THREAD

**Issue by pierluigilenoci** [kubeshop/botkube#484]
**Is your feature request related to a problem? Please describe.**

The configuration of the `resources` is frustrating. 

**Describe the solution you'd like**

It would be useful to allow to configure the `resources` section in the chart to add only the changes you want for certain types of `resources` and take the default configuration otherwise. Now the default `resources` value is an [array](https://github.com/infracloudio/botkube/blob/develop/helm/botkube/values.yaml#L40-L241) and it is not possible to select the single resource to change the configuration but you have to redefine the entire array of resources. 

**Describe alternatives you've considered**

No alternative

**Additional context**

Not relevant

**Comment by pierluigilenoci** [comment]
@PrasadG193 any news about this?

**Comment by pierluigilenoci** [comment]
@PrasadG193 @thijsdejong @vaibhavp could you please take a look?

**Comment by PrasadG193** [comment]
Hey @pierluigilenoci, could you please suggest what configuration format you are expecting? Feel free to ping me on Slack for wider discussion

**Comment by pierluigilenoci** [comment]
@PrasadG193 specifically, I have no clear ideas but maybe something better can be done with anchors, aliases, and merge keys.

**Comment by pierluigilenoci** [comment]
@PrasadG193 any news?

**Comment by pierluigilenoci** [comment]
@PrasadG193 any news?

**Comment by pierluigilenoci** [comment]
@ebrianne could you please take a look?

**Comment by pierluigilenoci** [comment]
@pkosiec @mszostok, could you please take a look?

**Comment by pierluigilenoci** [comment]
@pkosiec, could you please provide feedback?

**Comment by pkosiec** [comment]
We've updated the Helm chart configuration in Botkube 1.0+. Until anyone have better idea how and what we can improve, we can't do anything about it. Map is a no-go as then people would need to reset the default config which is way worse than the current array.

Feel free to create a brand-new issue and contribute to the project with specific configuration changes which won't make the life easier for people who heavily customize the configuration.

Cheers!
