### ISSUE TITLE
Define the channel at the namespace level 

### ISSUE THREAD

**Issue by pierluigilenoci** [kubeshop/botkube#486]
**Is your feature request related to a problem? Please describe.**

Clusters are shared resources, most often by many teams, and each team needs to define its own channel. It is very frustrating to have to add BotKube annotation to all resources manually and it is also prone to errors. 

**Describe the solution you'd like**

Teams are often separated by namespaces. It would be very useful to be able to define the default channel for communications at the namespace level so that all resources within inherit the channel. Obviously then if some object inside wants to redefine the channel it makes sense that it can be done.

**Describe alternatives you've considered**

No alternative.

**Additional context**

Not relevant.

**Comment by pierluigilenoci** [comment]
I'm sorry I'm not an expert in GO otherwise I would have tried to do a PR but looking at the code I would say that this feature could be implemented in the filter for the namespace. When checking whether the namespace needs to be "mutated" it can also be checked whether the namespace has a default channel to apply. My 2 cents.

**Comment by pierluigilenoci** [comment]
@PrasadG193 any news about this?

**Comment by pierluigilenoci** [comment]
@PrasadG193 @thijsdejong @vaibhavp could you please take a look?

**Comment by pierluigilenoci** [comment]
@PrasadG193 could you please take a look?

**Comment by pierluigilenoci** [comment]
@PrasadG193 any news?

**Comment by pkosiec** [comment]
Closing as it was implemented in https://github.com/kubeshop/botkube/issues/596. BotKube 0.13 is just around the corner, stay tuned!
