### ISSUE TITLE
[BUG] v1/nodes error with message empty

### ISSUE THREAD

**Issue by webjoel** [kubeshop/botkube#494]
There was an error in the cluster, BotKube added it to Slack, but the error message was empty.
![Captura de tela de 2021-06-15 15-09-55](https://user-images.githubusercontent.com/1946348/122102744-23b56b00-cdec-11eb-9912-2c3411890bec.png)

**This error is occurring every 6 hours:**

![Captura de tela de 2021-06-16 08-40-14](https://user-images.githubusercontent.com/1946348/122212748-966f2680-ce7e-11eb-97eb-5c0e147cac2f.png)

**Additional info:**
- Version: 0.12.1

**Comment by rahulchheda** [comment]
Seems like `Message` for these events would be empty.
Should we improve botkube to send Reasons aswell? WDYT @PrasadG193

**Comment by pkosiec** [comment]
Hi all,
Please verify if this issue still occurs in Botkube 1.0.1. If yes, please create another issue. Thank you!
