### ISSUE TITLE
add some badges to the readme

### ISSUE THREAD

**Issue by abhaysingh003** [kubeshop/botkube#502]
**Is your feature request related to a problem? Please describe.**
Add some badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

**Describe the solution you'd like**
I will add some badges at the top and also will add links related to them so that the README.md file will look more interactive and awesome.

**Comment by mszostok** [comment]
We already reworked the README.md. Currently, we don't have plans to add more badges. Thanks!
