### ISSUE TITLE
Collect analytics

### ISSUE THREAD

**Issue by PrasadG193** [kubeshop/botkube#506]
**Is your feature request related to a problem? Please describe.**

Add a way to collect analytics that will help us deciding roadmaps for BotKube development 

> **Note**
> Edited by @pkosiec - as agreed in https://github.com/infracloudio/botkube/pull/625,  the following list declares the scope of this task.

### To do

- [x] Set up Google Analytics and Twilio Segment accounts @pkosiec 
  - Ensure proper access rights

- [x] Implement collecting analytics in BotKube @pkosiec 
  - [x] Collect analytics listed in Initial data to collect section of the proposal
      - https://github.com/kubeshop/botkube/pull/640
      - https://github.com/kubeshop/botkube/pull/644
  - [x] Use [Segment Go Library](https://segment.com/docs/connections/sources/catalog/libraries/server/go/)
  - [x] Enabled by default
  - [x] Make sure users can opt out:
    - a dedicated env variable supported by app
    - a dedicated Helm chart property
  - [x] Document changes on botkube.io: https://github.com/kubeshop/botkube-docs/pull/96
    - Update [privacy policy](https://github.com/infracloudio/botkube-docs/blob/master/content/privacy.md) and describe data we collect
    - Describe configuration - how to opt-out
      - Consider describing it also for each installation document

- [x] Implement analytics on the website @pkosiec https://github.com/kubeshop/botkube-docs/pull/90
  - Use Google Analytics 4
  - If needed: Add cookie banner (some reports say Google Analytics 4 are cookieless, but I also read on official website that `gtag.js` library uses first-party cookies, so a user consent might be also needed)
  - Document changes: Update [privacy policy](https://github.com/infracloudio/botkube-docs/blob/master/content/privacy.md) and describe data we collect 

- [ ] Communicate changes @brampling
  - Write announcement on Slack to gather feedback before/during implementation (before 0.13 release)
  - Explain the reason of introducing the analytics
  - Point to the [epic issue](https://github.com/infracloudio/botkube/issues/506) for further discussion
  - If necessary, schedule a public meeting to discuss the changes
  - Mention analytics in BotKube 0.13 GitHub release description

**Comment by pkosiec** [comment]
I agree, this is a very nice idea. Few thoughts from my side:

- To investigate which solution should be used: Google Analytics, segment.io, others?
- There should be an option to opt-out during installation
- Collect how many installations are there
- Nice to have: Additional metrics: which kind of events are most used
- Update privacy policy on botkube.io

**Comment by PrasadG193** [comment]
@pkosiec Let me start creating a draft for this. We can collaborate on the events we want to gather.

**Comment by pkosiec** [comment]
Hi @PrasadG193, have you started already working on this? I'm going to do a little research around this topic and I will post my findings here in the issue comment or a dedicated markdown doc.

After we all have an agreement around the scope of this task, along with @mszostok we can take care of the implementation 🙂 Cheers!

**Comment by pkosiec** [comment]
Here's a short document with my findings from the short investigation: https://github.com/infracloudio/botkube/pull/625. Everybody is invited to post feedback under that PR 🙂

**Comment by pkosiec** [comment]
Closing this epic as implementation is finalized. The change will be communicated by @brampling when we're closer to the release.
