### ISSUE TITLE
[BUG] Rejecting mapping update to [botkube-2021-09-06] as the final mapping would have more than 1 type: [_doc, botkube-event] 

### ISSUE THREAD

**Issue by dsaydon90** [kubeshop/botkube#521]
**Describe the bug**
```
ERRO[2021-09-06T07:50:40Z] Failed to post data to els. Error:elastic: Error 400 (Bad Request): Rejecting mapping update to [botkube-2021-09-06] as the final mapping would have more than 1 type: [_doc, botkube-event] [type=illegal_argument_exception] 
```
> The ability to have multiple mapping types per index has been removed in 6.0. New indices will be restricted to a single type. This is the first step in the plan to remove mapping types altogether. Indices created in 5.x will continue to support multiple mapping types.

from: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/breaking-changes-6.0.html

**To Reproduce**

1. use `elasticsearch` communication
2. create `index template` to `botkube-*` index pattern with default options
3. create kibana `Index Pattern` with `Time field: 'TimeStamp'`
3. wait couple of days until you will get the bug above

version: `botkube-v0.12.2`
elastic cloud: `7.14.0`

**Comment by pkosiec** [comment]
Hey @dsaydon90, thanks for reporting this issue. As it's been already quite some time, I'm closing this. Please test the latest Botkube and create another issue if you're still facing this problem. I know we fixed problems with event mapping a while ago.
