### ISSUE TITLE
Reduce event noise in default installation

### ISSUE THREAD

**Issue by vishal-biyani** [kubeshop/botkube#534]
Today when a user installs BotKube, there is a bunch of configuration which allow the user to finetune the events they get. But by default too BotKube send quite a bit of events which may not be something that all users care about. To reduce event noise, we should add some defaults to the vanilla installation. One immediate thing could be that only error events are notified and not rest of levels.

There is a larger issue of routing messages based on namespaces/annotations or other mechanisms which will be discussed in a separate issue.

**Comment by pkosiec** [comment]
Completed in https://github.com/kubeshop/botkube/issues/711
