### ISSUE TITLE
[BUG] FATA[2021-11-15T01:28:56Z] stat /home/botkube/.kube/config: no such file or directory 

### ISSUE THREAD

**Issue by nomadcalendar** [kubeshop/botkube#541]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

### Description:

When launching deploy-all-in-one.yaml from https://github.com/infracloudio/botkube/blob/master/deploy-all-in-one.yaml, I get the following issue:

INFO[2021-11-15T01:36:01Z] Registering the filter ImageTagChecker       
INFO[2021-11-15T01:36:01Z] Registering the filter IngressValidator      
INFO[2021-11-15T01:36:01Z] Registering the filter NamespaceChecker      
INFO[2021-11-15T01:36:01Z] Registering the filter NodeEventsChecker     
INFO[2021-11-15T01:36:01Z] Registering the filter ObjectAnnotationChecker 
INFO[2021-11-15T01:36:01Z] Registering the filter PodLabelChecker       
INFO[2021-11-15T01:36:01Z] Starting controller                          
INFO[2021-11-15T01:36:01Z] Starting slack bot                           
INFO[2021-11-15T01:36:01Z] Starting upgrade notifier                    
FATA[2021-11-15T01:36:01Z] stat /home/botkube/.kube/config: no such file or directory 

### Steps to reproduce the issue:

1. kubectl create -f deploy-all-in-one.yaml
2. kubectl get pods --all-namespaces
3. botkube       botkube-695bfd5b7-jqhgw                                           0/1     CrashLoopBackOff   1 
4. kubectl logs botkube-695bfd5b7-jqhgw -n botkube

INFO[2021-11-15T01:36:01Z] Registering the filter ImageTagChecker       
INFO[2021-11-15T01:36:01Z] Registering the filter IngressValidator      
INFO[2021-11-15T01:36:01Z] Registering the filter NamespaceChecker      
INFO[2021-11-15T01:36:01Z] Registering the filter NodeEventsChecker     
INFO[2021-11-15T01:36:01Z] Registering the filter ObjectAnnotationChecker 
INFO[2021-11-15T01:36:01Z] Registering the filter PodLabelChecker       
INFO[2021-11-15T01:36:01Z] Starting controller                          
INFO[2021-11-15T01:36:01Z] Starting slack bot                           
INFO[2021-11-15T01:36:01Z] Starting upgrade notifier                    
FATA[2021-11-15T01:36:01Z] stat /home/botkube/.kube/config: no such file or directory 

### Describe the results you received:

INFO[2021-11-15T01:36:01Z] Registering the filter ImageTagChecker       
INFO[2021-11-15T01:36:01Z] Registering the filter IngressValidator      
INFO[2021-11-15T01:36:01Z] Registering the filter NamespaceChecker      
INFO[2021-11-15T01:36:01Z] Registering the filter NodeEventsChecker     
INFO[2021-11-15T01:36:01Z] Registering the filter ObjectAnnotationChecker 
INFO[2021-11-15T01:36:01Z] Registering the filter PodLabelChecker       
INFO[2021-11-15T01:36:01Z] Starting controller                          
INFO[2021-11-15T01:36:01Z] Starting slack bot                           
INFO[2021-11-15T01:36:01Z] Starting upgrade notifier                    
FATA[2021-11-15T01:36:01Z] stat /home/botkube/.kube/config: no such file or directory 

### Version of Kubernetes:

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T01:02:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by PrasadG193** [comment]
@nomadcalendar could you please try to install BotKube in `botkube` namespace? If you want to install it in a different namespace, you might have to update the manifest.

**Comment by nomadcalendar** [comment]
@PrasadG193 it is already in the botkube namespace.

**Comment by PrasadG193** [comment]
@nomadcalendar have you updated Slack token and channel in the manifest? I am assuming you are using Slack integration.

**Comment by nomadcalendar** [comment]
@PrasadG193 it's not about the Slack integration unfortunately, as the container overall is not launching citing the missing config. Tried assigning a config path - no luck. It's an install of the newest stable using the guidance from the docs step by step.

**Comment by nomadcalendar** [comment]
https://raw.githubusercontent.com/infracloudio/botkube/master/deploy-all-in-one.yaml depkoyment using this config is failing @PrasadG193

**Comment by pkosiec** [comment]
Hi @nomadcalendar,
We reduced supported ways how to install BotKube, and now the Helm 3 is the go-to solution. We've tested that with and without mounting a custom Kubeconfig, and it works fine. Please follow the instructions on botkube.io and see if the problem still persists.

Closing this issue, but feel free to reopen in case of any issues. Cheers!
