### ISSUE TITLE
Provide multiple channels 

### ISSUE THREAD

**Issue by Lion916** [kubeshop/botkube#542]
**Is your feature request related to a problem? Please describe.**
We want to notify the chat software of error events, but at the same time notify ES of all events.Since we only care about message notifications for error events, follow-up analysis is required for all events

**Describe the solution you'd like**
It would be nice if you could simply configure it in a configuration file

**Comment by wangshuai-1806** [comment]
**Describe alternatives you've considered**

I wrote custom filter but it would be nice to have built-in filter.
To solve this problem, we now have two instances deployed, one to send messages to chat and the other to send messages to Elasticsearch.

This split deployment doesn't feel like the best solution.

I want to do an interception on notification to the specific notifier.

Can you give me some advice? @PrasadG193

**Comment by PrasadG193** [comment]
@wangshuai-1806 we are working on a more robust solution. Please keep watch on the future releases :)

**Comment by wangshuai-1806** [comment]
@PrasadG193 Thank you for your reply, I will continue to pay attention to the follow-up version

**Comment by dsaydon90** [comment]
Related https://github.com/infracloudio/botkube/issues/508 ?

**Comment by pkosiec** [comment]
Closing as it was implemented in https://github.com/kubeshop/botkube/issues/596. BotKube 0.13 is just around the corner, stay tuned!
