### ISSUE TITLE
[feat]: allow disabling event monitoring completely

### ISSUE THREAD

**Issue by ShragaUser** [kubeshop/botkube#570]
**Is your feature request related to a problem? Please describe.**

is there an option to completely disable event monitoring with botkube?
I want to use this mainly as a debug tool to run kubectl commands from slack.
I’ve configured it to only look at a specific namespace and resource (trying to mitigate the amount of events) - but it seems to only affect notifications, the bot still listens to all the events but ignores them.
I have a pretty big cluster, so this is just putting load on the unnecessarily.

**Describe the solution you'd like**
helm chart setting to disable event monitoring from the Informer Controller.

**Describe alternatives you've considered**

**Additional context**
Not being able to disable or filter events sent to the event manager creates a load on the service.
this load is leading to client api throttling - which in turn makes all BotKube kubectl commands to take a long while to process (without immediate acknowledgment that the command was even received).
for example:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/18091546/162226192-1533dcd2-b404-47c4-92d7-c786609c25e5.png">
after about a minute.

**Comment by anil-venkata** [comment]
i am facing the same issue, Whenever the botkube pod restarts, notifier automatically getting started and the messages are flooding like anything in the slack channel. 

For this to resolve you can enable the onlt events that you want to notify in the configmap `botkube-configmap` . In my case i deleted all the events for all the resources. 

For example, 

From this config 

```    
 - name: apps/v1/deployments
        namespaces:
          include:
            - all
          ignore:
            -
        events:
          - create
          - update
          - delete
          - error
        updateSetting:
          includeDiff: true
          fields:
            - spec.template.spec.containers[*].image
            - status.availableReplicas
   ```

to this config

```
     - name: apps/v1/deployments
        namespaces:
          include:
            - all
          ignore:
            -
        events:
          - 
 ```

Let me know if this helps. Thanks.

**Comment by ShragaUser** [comment]
@anil-venkata Hey! Thanks for the help! I actually fixed it myself by setting the bot to listen to a namespace thats empty (has no pods / deployments etc') so I don't get any notifications (did this in the helm chart values file).

But my issue is still there - when looking at the bots pod logs you can see that it's still "reacting" to all events in the cluster, it filters them so that a notification isn't created, but it still monitors events unnecessarily. 

This is just added stress on the api and the pod, utilizing resources without need. 

I'd like there to be a `cfg.monitoringEnabled` that defined if we sign up from events from the k8s api.

**Comment by ezodude** [comment]
This has been further investigated and is now being tracked in https://github.com/kubeshop/botkube/issues/674 🙂

**Comment by ezodude** [comment]
Closing this issue as Triage is complete. Thanks for raising this 👍
