### ISSUE TITLE
Release 0.13 and promote it

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube#595]
As this will be a first feature-packed release since ~1,5 years, it would be great to promote it and also gather feedback from the community. Here are some ideas:

### Release
- [x] Revert docs PR - https://github.com/kubeshop/botkube-docs/pull/133
    - https://github.com/kubeshop/botkube-docs/pull/112/files 
    - https://github.com/kubeshop/botkube-docs/pull/127
- [x] Go through the release process instruction (https://github.com/infracloudio/botkube-docs/pull/74) and release 0.13
    - Consider alpha/beta releases to gather community feedback 
- [x] Describe any breaking changes in the GitHub release

### Community-related tasks (nice to have)
- prepare survey for BotKube users (to know how the community uses BotKube, and build priorities for future based on the feedback)
    - Loosely related issue: #506
- create a blog post (target location: to discuss)
- cross-post the blog post (e.g. Medium, Dev.to)
- Share the news in social media (e.g. Reddit, Hacker News, LinkedIn, Twitter)
- Prepare an online meetup presentation based on 0.13 features
- Think about new places for where BotKube can be promoted.
    - For example, awesome lists. Project is already mentioned in https://github.com/ramitsurana/awesome-kubernetes, but there might be additional lists where it can be promoted as well

**Comment by mszostok** [comment]
## Release activities

| Task                                                                                | Assignee   | Note                                                                                                                                                                                                                  |
|-------------------------------------------------------------------------------------|------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Create branch `release-0.13`                                                        |            | This will be the first time that we do that, so first to the dry-run on your fork.                                                                                                                                    |
| Create the `0.13.0-rc.1`                                                            |            | Ensure that it's marked as `pre-release` on GitHub releases page.                                                                                                                                                     |
| Test the release candidate                                                          |            |                                                                                                                                                                                                                       |
| Prepare PR with updated BotKube documentation                                       |            | We introduce breaking changes, so we need to change the `helm install` command. Currently, the Installation docs uses v0.12.4 version. Test each command locally. Also revert docs changes as described in the issue. |
| Check if migration note was rendered correctly                                      |            | It's our first time when we use that.                                                                                                                                                                                 |
| Create a blog post and cross-post it (e.g. Medium, Dev.to)                          | Blair (?) |                                                                                                                                                                                                                       |
| Share the news in social media (e.g. Reddit, Hacker News, LinkedIn, Twitter, Slack) | Kelly (?) |                                                                                                                                                                                                                       |

If everything go well, we can create the `0.13.0` release. If bugs are detected, we need to contribute all required fixes both to the `main` and `release-0.13` branches, cut a new RC and re-test it.

**Comment by mszostok** [comment]
## Testing

| Task          | Assignee | Note                                                               |
|---------------|----------|--------------------------------------------------------------------|
| Slack         | -        | It's tested by our e2e test. IMO we don't need to test it further. |
| Mattermost    |          |                                                                    |
| Discord       |          |                                                                    |
| Elasticsearch |          |                                                                    |
| Webhook       |          |                                                                    |
| MS Teams      |          |                                                                    |


Ping

   ```
   @BotKube ping
   ```
### Filters

1. List
   ```
   @BotKube filters list
   ```
   exp output:
   ```
   FILTER                  ENABLED DESCRIPTION
   NodeEventsChecker       true    Sends notifications on node level critical events.
   ObjectAnnotationChecker true    Checks if annotations <http://botkube.io/*|botkube.io/*> present in object specs and filters them.`
   ```
1. Test ObjectAnnotationChecker filter:
   - Disable
        ```
        @BotKube filters disable ObjectAnnotationChecker
        ```
   - TODO: create object
   - Enable
       ```
       @BotKube filters enable ObjectAnnotationChecker
       ```
   - TODO: create object

### Commands
1. Test on `team` and `admin` channels
    ```
    @BotKube commands list
    ```
2. With cluster name
    ```
    @BotKube commands list --cluster-name gke-stage
    ```

### Kubectl executor

### Recommendations


### K8s source
- Check if namespace is properly `included` both with regex and exact name
- Check if namespace is properly `excluded` both with regex and exact name

1. Event ConfigMaps
  - Should work for `(botk.*|default)`
     ```
     kubectl create configmap my-config-botkube --from-literal=key1=config1 -n botkube
     ```
     ```
     kubectl create configmap my-config-def --from-literal=key1=config1 -n default
     ```
     ```
     kubectl create ns botkubik && kubectl create configmap my-config-botkubik --from-literal=key1=config1 -n botkubik
     ```
  - Shouldn't work for other that `(botk.*|default)`:
    ```
    kubectl create ns foo && kubectl create configmap my-config-foo --from-literal=key1=config1 -n foo
    ```
    ```
    kubectl create ns xyz && kubectl create configmap my-config-xyz --from-literal=key1=config1 -n xyz
    ```
1. Pods
   - Should work for all NS except `(".*-system", "default")`:
      ```
      kubectl create ns foo && kubectl run nginx --image nginx -n foo
      ```
      ```
      kubectl create ns baz && kubectl run nginx --image nginx -n baz
      ```
      ```
      kubectl create ns test && kubectl run nginx --image nginx -n test
      ```
   - Shouldn't work for `(".*-system", "default")`:
      ```
      kubectl create ns istio-system && kubectl run nginx --image nginx -n istio-system
      ```
      ```
      kubectl create ns botkube-system && kubectl run nginx --image nginx -n botkube-system
      ```
      ```
      kubectl create ns argo-system && kubectl run nginx --image nginx -n argo-system
      ```
      ```
      kubectl run nginx --image nginx -n default
      ```

**Comment by ezodude** [comment]
Is there a requirement for a 'Migrating to BotKube 0.13.0' guide?

Or is that what the upcoming Blog Post is designed to do? Also, found a related description [in this issue](https://github.com/kubeshop/botkube/issues/614).

**Comment by ezodude** [comment]
Added myself for 2 integrations, will start them on Thursday 25th.

But if someone gets there faster (because of Timezone start time differences) feel free to grab them.
