### ISSUE TITLE
Enable notifier automatically for Teams channel

### ISSUE THREAD

**Issue by RagingTonberry** [kubeshop/botkube#605]
**Is your feature request related to a problem? Please describe.**
We would like to probably deploy BK automatically in multiple clusters, but starting notifications requires a manual step.

It would be nice if it could send notifications automatically without being told to start. I noted in the code that a new instance of botkube will always be disabled at startup.

**Describe the solution you'd like**
Ideally, the bot could start sending notifications as soon as it is connected to teams (however that happens) without being told to start notifications. Perhaps this could be set via a configuration option with helm or similar?

**Describe alternatives you've considered**
Looked at a bunch, and even considered writing my own but BotKube is already 99% of the way to what I would like.

**Additional context**
Nope, that about covers it.

**Comment by RagingTonberry** [comment]
And just as a minor update, when you update the configmap the bot restarts and the teams notification halts. That's a bit of a problem for continuity of notification.

**Comment by PrasadG193** [comment]
@RagingTonberry it is actually a limitation from the way MS Team bot integration work. The communication needs to be initiated by MS Teams client side so that BotKube gets the comm ref. Which is used to communicate.

You can actually turn off automatic restart on configmap changes. But the new config won't be reflected

**Comment by RagingTonberry** [comment]
@PrasadG193 Mmm, I had a feeling you were going to say something like that. Is it possible to look into why the webhook doesn't work for teams as one might expect? That would also be a good solution for me. At the moment, it produces blank output. See #321 #469 
Cheers!
Feel free to close in favor of one of those others.

**Comment by pkosiec** [comment]
Hi, I'm closing this issue in favor of https://github.com/kubeshop/botkube/issues/705, as we want to investigate how we can improve the integration. Cheers!
