### ISSUE TITLE
Executor Extensibility

### ISSUE THREAD

**Issue by brampling** [kubeshop/botkube#650]
A BotKube user must be able to run helm (or other CLI tools) from the BotKube chat interface. This allows them to manage the parts of their Kubernetes cluster that are not manageable by kubectl. This means they can respond to and troubleshoot more issues directly with BotKube rather than moving to a terminal window.

A BotKube admin must be able to add supported CLI tools to the BotKube configuration, thus making them available to BotKube users.

**AC**

- A BotKube admin can add CLI commands (e.g. helm) to the BotKube configuration
- A BotKube user can run the added CLI commands similarly to `kubectl` today
- ~`@botkube commands list `shows the installed commands~ replaced with https://github.com/kubeshop/botkube/issues/891

- [x] https://github.com/kubeshop/botkube/issues/716

**Comment by mszostok** [comment]
### Status
Done 
- [The executor plugin manager](https://github.com/kubeshop/botkube/issues/838).
- Plugin release process.
- The first [`helm` executor](https://github.com/kubeshop/botkube/issues/843) plugin.

The only thing that left is provided more documentation on how to create an executor plugin and how to build the plugin index. This work will be tracked in this issue https://github.com/kubeshop/botkube/issues/839.
