### ISSUE TITLE
Run BotKube as a debug tool only

### ISSUE THREAD

**Issue by ezodude** [kubeshop/botkube#674]
## Overview

I only want to run BotKube to debug my cluster by executing `kubectl` commands. And, I do not want to be notified of any events. 

Related to issue #570

### The problem

This seems to work when BotKube is set with ...

- `sources.'k8s-events'.kubernetes.resources` to an empty array. (v0.12.4+ / dev)
- `config.resources` to an empty array (v0.12.4).
- `sources.'k8s-events'.kubernetes.resources.resource.events` to an empty array. (v0.12.4+ / dev)
- `config.resources.resource.events` to an empty array (v0.12.4).

as no events are notified in any channels.

**BUT** ... [BotKube has an extra Informer](https://github.com/kubeshop/botkube/blob/e082c01929a90519d2700b63e9007e42df34ded4/pkg/controller/controller.go#L132) (Cluster Informer), that cannot be user configured, which:

- Listens to `warning` and `info` events across the Kubernetes cluster
- Receives these events
- Checks whether the event should be sent or not based on the `resources` config
- Sends the event if there is no contradiction with the config
- OR .. ignores the event based on the config

These events are cached and processed consuming system resources. In huge clusters, this leads to throttling the execution of `kubectl` commands.

```shell
I0407 14:39:32.538737
21 request.go:665] Waited for 1.19669725s due to client-side throttling, not
priority and fairness, request: GET:https://172.20.0.1:443/apis/discovery.k8s.io/v1betal?timeout=32s
```

Again, see Issue #570 for reference.

### The solution

Provide a setting in the Helm chart that stops Kubernetes cluster monitoring. This should stop all monitoring when used with the existing `resources` config.

I propose for the setting to be:

```yaml
sources:
  'k8s-events':
    clusterMonitoring:
        enabled: true
```

This should bypass creating the Cluster Informer.

### Future solution 

(Requires extra discovery work and possibly more involved refactoring)

The ideal here is a better Informer solution that allows for finer grained event monitoring.

This should:
- Exclude any resource ignored events from the Cluster Informer.
- More access to configure the Cluster Informer.

Such a solution will avoid unnecessary caching and system load.

## Acceptance Criteria

- Run `kubectl` commands without encountering any throttling.
- Reduce BotKube system load.

## Reason

Without this feature, it is very hard to enable BotKube `kubectl` execution in large production clusters.

**Comment by pkosiec** [comment]
Nice investigation 👍 The solution looks good to me, but I'd consider different property name. I think the `clusterMonitoring` is too general and might be confusing what does it mean. Also, it should be scoped under `kubernetes` (`sources.k8s-events.kubernetes`) as it relates to the Kubernetes event source.

At the end of the day the informer is for Kubernetes events, so I'd try to stick close to the original behavior. What do you think about `events`?

```yaml 
sources:
  'k8s-events':
    kubernetes:
        events:
            enabled: true
```

I think that would explain more what's the property about. Let me know what you think!

**Comment by ezodude** [comment]
@pkosiec I like very much!

**Comment by ezodude** [comment]
After the 0.13.0 release, this issue is no longer relevant as the method by which informers are registered has been redesigned and improved upon.

This work had to be completed to [enable the use of sources](https://botkube.io/configuration/source/).

## To stop all events using sources config

This is the simplest and fastest approach: update your config in `values.yaml` with: `sources: []`.

## To stop all events using communication providers

Keeping the `sources` config intact, go through all communication providers, e.g. `communications.<group>.slack.channels.<channel>`, and set `…bindings.sources: []`.

You’ll have to do this for any configured enabled or disabled communication providers.

**Comment by ezodude** [comment]
Marking as resolved based on [latest comments](https://github.com/kubeshop/botkube/issues/674#issuecomment-1231332148).
