### ISSUE TITLE
Role-based Access Control

### ISSUE THREAD

**Issue by brampling** [kubeshop/botkube#675]
Currently there is no strong access control on the Kubernetes side of the BotKube configuration. Installing BotKube creates a ServiceAccount with full Kubernetes access. Access control (such as allowed `kubectl` verbs) is configured in the BotKube configuration. All BotKube users have the same access level.

Access control should be enhanced in two ways:

- Configurable both on the Kubernetes side in general (i.e. BotKube ServiceAccount is restricted by k8s security policies)
- Configurable on a per-user basis (i.e. a specific user of BotKube maps to a role / set of permissions)

**Comment by brampling** [comment]
Related:
https://github.com/kubeshop/botkube/issues/254
https://github.com/kubeshop/botkube/issues/227

**Comment by pkosiec** [comment]
Closing as the https://github.com/kubeshop/botkube/issues/712 has been implemented 👍
