### ISSUE TITLE
Support routing notifications to a given channel based on Kubernetes Sources

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube#676]
## Overview

User should be able to define different notification sources per a given channel based on the Kubernetes namespace. See the proposal section: https://github.com/kubeshop/botkube/blob/main/docs/proposal/2022-06-14-configuration-bindings.md#route-notifications-to-a-given-channel-based-on-the-kubernetes-namespace

Currently, the sources bindings introduced in new config are not supported:

https://github.com/kubeshop/botkube/blob/95918ec778dfb4866366bbc96eed389e870df8a9/helm/botkube/values.yaml#L328-L329

The scope of this task is to:
- support source bindings in all communication platforms
- ~support Kubernetes event namespace filtering by another property for `kubernetes` source~ (This has been de-scoped)

## Acceptance Criteria

- ~Add new `namespace.include/exclude` property in the `sources.'group-name'.kubernetes` according to the proposal~ (This has been de-scoped)
- Ensure multiple source definitions are supported
- Support source bindings per channel / index for all communication platforms (bots and sinks)
- Update documentation on `botkube-docs` repo
- Add required unit and E2E tests

## Reason

See epic https://github.com/kubeshop/botkube/issues/596.

**Comment by ezodude** [comment]
Now in code exploration mode.

**Comment by pkosiec** [comment]
BTW @ezodude regarding the comments
> (This has been de-scoped)
I think there was a misunderstanding. I believe that's still a scope of this task, but this is definitely something to do in a follow-up PR (not in the first one) 🙂 And then we will have all parts together of the whole multi-workspace/multi-channel configuration epic.

**Comment by pkosiec** [comment]
Ok, I see you extracted the namespaces functionality to a separate task. Closing it then 👍
