### ISSUE TITLE
Rework K8s resource annotations for controlling notifications

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube#690]
## Overview

Currently, there are two annotations which control notifications:
- `botkube.io/disable: true/false` - whether to send notifications about a given resource
- `botkube.io/channel: {channel}` - custom channel where the notifications are routed to. But the behavior is inconsistent:
    
    **This is supported by Slack and Mattermost only.** In case of Mattermost, the annotation value should contain:
    - for Mattermost: channel ID,
    - for Slack: channel name.

We should straighten that up.

## Acceptance Criteria

- Rethink the annotation names and theirs values to allow extensibility
    - Take into account newer config
    - support multiple channels across different communications, e.g. `botkube.io/communications.slack.channels: "general,random"`
    - Take into consideration whether a target channel should be "authorized", that is, defined inside the static configuration (discussion: https://github.com/kubeshop/botkube/issues/250)
    - Instead of `botkube.io/disable`, maybe we should have different annotation to exclude a given resource notification from a given source? As we'll have multiple sources support in #676, it could make sense... 🤔
- Support all communication platforms
- Update documentation

## Reason

Currently, this feature is inconsistent and limited to two communicators. We should aim to have feature parity across all integrations.

**Comment by mszostok** [comment]
As we are going to extract the K8s source as a plugin, such functionality will be hard to keep. As discussed with @pkosiec and @huseyinbabal we are going to remove support Botkube specific K8s annotations:
- `botkube.io/disable: true/false`
- `botkube.io/channel: {channel}`


Instead, you will be able to still annotate your objects and use `annotations` property under k8s source to filter by.

This will be done as a part of #840
