### ISSUE TITLE
Unify BotKube commands naming

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube#703]
## Overview

Currently, BotKube has the following list of commands:

```
BotKube Help

Usage:
    @BotKube ping [--cluster-name <cluster-name>]
    @BotKube commands list  (on BotKube v0.11.0+)
    @BotKube <kubectl command without kubectl prefix> [--cluster-name <cluster_name>]
    @BotKube notifier [stop|start|status|showconfig]
    @BotKube filters [list|enable|disable] [filter-name]

Description:

Cluster Status:
    - List all available Kubernetes Clusters and check connection health.
    - If flag specified, gives response from the specified cluster.

    Example:
        @BotKube ping
        @BotKube ping --cluster-name mycluster

Allowed kubectl commands list:
    - Show allowed kubectl commands as per the BotKube configuration

    Example:
        @BotKube commands list

Kubectl commands:
    - Executes kubectl commands on k8s cluster and returns output.

    Example:
        @BotKube get pods
        @BotKube logs podname -n namespace
        @BotKube get deployment --cluster-name cluster_name

    Allowed kubectl commands:
        For BotKube v0.11.0+:
            Check allowed commands with '@BotKube commands list'
        For older versions:
            Allowed commands are - get, top, cluster-info, describe, explain, logs, version, auth, api-resources, api-versions, diff

Notifier commands:
    - Commands to manage incoming notifications (Runs only on configured channel).

    Example:
        @BotKube notifier stop          Stop sending k8s event notifications to Slack
        @BotKube notifier start         Start sending k8s event notifications to Slack
        @BotKube notifier status        Show running status of event notifier
        @BotKube notifier showconfig    Show BotKube configuration for event notifier

Filters commands:
    - Command to manage filters run on K8s events (Runs only on configured channel).

    Example:
        @BotKube filters list                     Show list of available filters
        @BotKube filters disable ImageTagChecker  Disable filter
        @BotKube filters enable ImageTagChecker   Enable filter

Options:
    --cluster-name                  Get cluster specific response
```

You can see, that for example `@BotKube notifier showconfig` doesn't follow the pattern for other commands. This is something which would be great to fix.

## Acceptance Criteria

- [x] Go through the list of commands and prepare final naming convention accepted by the team @lpetkov
    - For example, `@BotKube commands list` and `@BotKube notifier showconfig` - maybe it should be just one command, e.g. `@BotKube config`?
    - Consider requiring `kubectl` at the beginning of the commands - to support more executors #650 
- [x] Implement the solution (https://github.com/kubeshop/botkube/issues/703#issuecomment-1308613253
- [x] Support aliases for different command groups (e.g. `filters` -> `filter`)
- [x] Document breaking changes - list a table with old and new commands (under release? On docs.botkube.io as well?)
- [x] Ensure the commands we use internally are up to date (especially the interactive commands for Socket Slack)
- [x] Ensure the telemetry is still properly reported, even for new commands (like `@Botkube status sourcebindings`)

## Reason

To improve UX, we should have consistent commands naming.

**Comment by brampling** [comment]
Can we add the misfit /botkubehelp command to this?

Also, @lpetkov to do design review on this.

**Comment by pkosiec** [comment]
@brampling Good question - there's a separate task https://github.com/kubeshop/botkube/issues/393 but we can move its scope here as well, to form an epic issue 👍 Let me know if I should merge this.

Yes, @lpetkov help here would be much appreciated!

**Comment by lpetkov** [comment]
I propose to follow the following syntax: 
`@Botkube [command/verb] [optional secondary command] [--option="string"]`

### General commands: 
`@Botkube ping [--cluster="string"]` - Ping a cluster
`@Botkube help` - Print help menu
`@Botkube kc|kcc|kubectl [command] [TYPE] [NAME] [flags]` - Run kubectl commands
`@Botkube status`  - Show running status of event notifier
`@Botkube config` - Show bot configuration

### List 
`@Botkube list [filters|filter|flr]` to list all filters
`@Botkube list [commands|cmd]` to list all commands
### Enable
`@Botkube enable` to enable notifications in a channel
`@Botkube enable [filters|filter|flr] filterName` to enable a filter
`@Botkube enable [kubectl|kc|k]` to enable kubectl support
### Disable 
`@Botkube disable` to disable notifications in a channel
`@Botkube disable [filters|filter|flr] filterName` to disable a filter
`@Botkube disable [kubectl|kc|k]` to disable kubectl support

### Edit
`@Botkube edit sourcebindings`

**Comment by brampling** [comment]
LGTM. Should we note that "kubectl" is a standard for other extensible executors? e.g.

`@Botkube helm|argo|etc. [command] [TYPE] [NAME] [flags]`

**Comment by pkosiec** [comment]
@lpetkov Looks good, but have 3 comments:

1. Missing `@Botkube enable/disable notifications/notif`.
2. IMHO `@Botkube status` should be `@Botkube status notifications`
3. Minor thing: I would return help on the `@Botkube` command (without any arguments) or some welcome message - currently we show `Unsupported command` error which is a bad UX IMO.
4. Regarding `enable kubectl`:

> @Botkube enable [kubectl|kc|k] to enable kubectl support

Are you sure that should be possible? We don't have such functionality, and the question is how it should work. If users can enable kubectl functionality for a given channel from the channel, that means there's a security issue. Later, if we have user  mapping, then yes, that could work.

**Comment by lpetkov** [comment]
@pkosiec 
1. In addition to `@botkube enable` which would do the same thing?
2. Why? What other status could there be?
3. Agreed.
4. Agreed, let's skip that for now. @mszostok and I were talking about it some time ago but we're not there yet.

**Comment by pkosiec** [comment]
@lpetkov 

1. Oh, right, I didn't explain it correctly. I think instead of `@Botkube enable` we could have `@Botkube enable/disable notifications/notif`to be consistent with other configurable parts of Botkube. IMHO it will be also more intuitive with other parts of configuration you can enable and disable.

As a user, I wouldn't know whether `@Botkube disable` disables both notifications and execution or just one part of it. With `notifications` it's all clear to me.

3. Same as above - it would be more clear that it's about notifications. IMHO Status could mean many things:

- show enabled notifications
- show source bindings for current channel
- show enabled commands for executor

If you add a resource name, the problem disappears (IMHO).

Does that make sense for you?

**Comment by lpetkov** [comment]
Addressing the feedback above:


`@Botkube [command/verb] [optional secondary command] [--option="string"]`

### General commands: 
`@Botkube` - same as `@Botkube help`
`@Botkube ping [--cluster="string"]` - Ping a cluster
`@Botkube help` - Print help menu
`@Botkube kc|kcc|kubectl [command] [TYPE] [NAME] [flags]` - Run kubectl commands
`@Botkube config` - Show bot configuration

### Status
`@Botkube status [notifications|notif]`  - Show running status of event notifier
`@Botkube status [k|kc|kcc|kubectl]`  - Show enabled commands/verbs/resource types for `kubectl` for the channel
`@Botkube status sourcebindings` - Show enabled source bindings for the channel
`@Botkube status` - **print event notifier status AND** display a message listing all `status` options (listed above)
 
### List 
`@Botkube list [filters|filter|flr]` to list all filters
`@Botkube list [commands|cmd]` to list all commands
`@Botkube list` - list all `list` options

### Enable
`@Botkube enable [notifications|notif]` to enable notifications in a channel
`@Botkube enable [filters|filter|flr] filterName` to enable a filter
`@Botkube enable` - list all `enable` options

### Disable 
`@Botkube disable [notifications|notif]` to disable notifications in a channel
`@Botkube disable [filters|filter|flr] filterName` to disable a filter
`@Botkube disable` - list all `disable` options


### Edit
`@Botkube edit sourcebindings`
`@Botkube edit` - list all `disable` options (alternatively, run `@Botkube edit sourcebindings` - **opinions**?)

**Comment by pkosiec** [comment]
Looks good! One small question

>  @Botkube status - **print event notifier status AND** display a message listing all status options (listed above)

Just curious: what is the reason for custom behavior and not just list all the possible options here, like with other `@Botkube {verb/}` commands? There still will be an option to set some aliases if someone wants to have a shorter command for `@Botkube status notifications`.

> @Botkube edit - list all disable options

I believe you meant `list all edit options` - but yeah, I like that it lists all possible options 👍

**Comment by lpetkov** [comment]
> Just curious: what is the reason for custom behavior and not just list all the possible options here, like with other @Botkube {verb/} commands? There still will be an option to set some aliases if someone wants to have a shorter command for @Botkube status notifications.

My assumption is that most of the time most of the user will want to quickly see the status of their notifications which is the most common reason people install the software in the first place. So let's give them that and all other potential options in case they are interested in something else.

**Comment by lpetkov** [comment]
One thing we discussed with @mszostok is that in terms of consistency it would be better to have the `config`command as 
`@Botkube show cfg|config|configuration` as that is more consistent with the verb-first approach.
