### ISSUE TITLE
Notification Noise Reduction

### ISSUE THREAD

**Issue by brampling** [kubeshop/botkube#711]
## Overview

This epic aggregates the subtasks needed for the complete feature.

## Reason

Much of the feedback we have received from BotKube users indicates that by default, BotKube notifications are too noisy. The low-criticality event notifications crowd out the most important notifications. A lot of manual configuration is required to tune the notification settings.

We want to improve the signal to noise ratio of notifications and give users easier tools to ensure they are getting the notifications that are most valuable to them.

## Acceptance Criteria

- [x] https://github.com/kubeshop/botkube/issues/710
- [x] https://github.com/kubeshop/botkube/issues/704

**Comment by mszostok** [comment]
All implementation related PRs were merged to the `main` branch.
