### ISSUE TITLE
Release using Argo CD always produces new `installationID`

### ISSUE THREAD

**Issue by mmalyska** [kubeshop/botkube#729]
## Description

I'm using `Argo CD v2.4.11+3d9e9f2` to deploy botkube with enabled autosync.
Every time I update my monorepo(repository with multiple chats that are deployed on my cluster) the `installationID` is generated fresh and botkube deployment gets updated what causes botkube notifications to stop working for a short while.
Argo CD is using `helm template` to generate resources to update in cluster, so probably lookup is not working.
Maybe a solution would be to allow inputting `installationID` in values, or if someone disables analytics do not generate `installationID`.

## Expected behavior

`installationID` should be not generated every time.

## Actual behavior

`installationID` is generated with each delpoyment.

## Steps to reproduce

Generate chart using `helm template`, then generate it again. Both generated resources have different `installationID`.

**Comment by pkosiec** [comment]
Hey @mmalyska, good news! We'll get rid of the installation ID at all as a part of #759. Stay tuned for BotKube 0.14! 🚀
