### ISSUE TITLE
Render plain text for messages sent in attachments and remove the header

### ISSUE THREAD

**Issue by mszostok** [kubeshop/botkube#750]
## Description

Currently, when a message is too big, we send it as file. For example:
- slack:  https://github.com/kubeshop/botkube/blob/11b5bc5326ee3e4fc9b70769747f2c526e026771/pkg/bot/slack.go#L293
- discord: https://github.com/kubeshop/botkube/blob/11b5bc5326ee3e4fc9b70769747f2c526e026771/pkg/bot/discord.go#L263
- etc.

## Expected behavior

- When a message is sent as file, we should render it as plaintext. The header should be removed from the file and printed directly in the message.

   <img width="579" alt="Screen Shot 2022-09-22 at 10 51 34" src="https://user-images.githubusercontent.com/17568639/191702917-9208398f-fa8f-4e15-b100-e173f61552ef.png">

- **Do that for all communicators.**
- Add e2e test to cover this case.

## Actual behavior

When a message is sent as file, we still render in Markdown format.
<img width="591" alt="Screen Shot 2022-09-22 at 10 52 09" src="https://user-images.githubusercontent.com/17568639/191702999-bf3b7995-c892-47b2-8851-b84c9ed6f582.png">

## Steps to reproduce

Install latest BotKube and run e.g. `@BotKube describe nodes` or `@BotKube logs <pod_name>`

[Example response.txt](https://github.com/kubeshop/botkube/files/9624031/Response.txt)

**Comment by ezodude** [comment]
Is this a regression? or is this how BotKube always worked?

**Comment by mszostok** [comment]
It's regression after introducing the interactive messages 😞

**Comment by ezodude** [comment]
Status update, work on [branch render-plain](https://github.com/ezodude/botkube/tree/render-plain).

### Completed 
- [x] Do that for all communicators.

### Pending
- [ ] Add e2e test to cover this case.
