### ISSUE TITLE
Parameter analytics.disable cannot be overriden when doing Helm chart upgrade

### ISSUE THREAD

**Issue by AliHas78** [kubeshop/botkube#753]
## Description

Currently when passing analytics.disable via command line or applied via custom yml file, analytics.disable set to true does not stick. Workaround was applying it via kubectl edit configmap botkube-analytics-config -n botkube.

## Expected behavior

 analytics.disable should be set to true

## Actual behavior

analytics.disable is false the default value

**Comment by pkosiec** [comment]
Hi @AliHas78,
I was able to successfully disable analytics with the following commands:

```bash
helm install botkube --version v0.13.0 botkube/botkube --namespace botkube --create-namespace -f /tmp/values.yaml
```
Where:
```yaml
analytics:
   disable: true
```

And also
```bash
helm install botkube --version v0.13.0 botkube/botkube --namespace botkube --create-namespace --set analytics.disable=true
```

In both cases the analytics were properly disabled. Could you please elaborate a bit more about the issue?

**Comment by AliHas78** [comment]
@pkosiec I just tested trying to enable it using below command,
` helm upgrade -f botkube-preset.yml --version v0.13.0 botkube --namespace botkube --create-namespace `.

Where botkube-preset.yml:
```
analytics:
   disable: false
```
log -
` time="2022-09-22T15:50:14Z" level=info msg="Analytics disabled via configuration settings."`

configmap shows botkube-analytics-config (which I set before as workaround)
```
apiVersion: v1
data:
  analytics.yaml: |
    analytics:
      disable: true
```

**Comment by pkosiec** [comment]
@AliHas78 Oh, I understand, so you encounter this issue when doing `helm upgrade` with different value. Fresh Installation works properly, as I tested all disable/enable scenarios.

I've just tested doing `install`, and then `upgrade` with different values. The new value is not taken into account indeed, so I confirm the bug.

It's because we have in the Helm template:

```
  {{- $previous := lookup "v1" "ConfigMap" .Release.Namespace $cfgMapName }}
  {{- if $previous }}
  analytics.yaml: |
    {{- index $previous.data "analytics.yaml" | nindent 4 }}
  {{- else }}
  analytics.yaml: |
    analytics:
      disable: {{ .Values.analytics.disable }}
      # anonymous unique UUID generated during chart installation
      installationID: "{{- uuidv4 -}}"
  {{ end }}
```

We just wanted to preserve the anonymous installationID. I'm sorry, that's a bug - I will resolve that tomorrow.
Thank you for pointing that out 👍

**Comment by pkosiec** [comment]
Hey @AliHas78, we decided to get rid of the installation ID in #759. So your issue will be resolved in the upcoming release (in a couple of weeks). Cheers!
