### ISSUE TITLE
Ability to ignore pod errors related to Ec2 spot instance use

### ISSUE THREAD

**Issue by AliHas78** [kubeshop/botkube#754]
## Overview

Currently we are using Ec2 spot instances which take time to spin up and cause false positive errors. To reduce noise in slack channel we would like a feature to ignore pod error related to,

`0/6 nodes are available: 1 Insufficient memory, 5 node(s) didn't match Pod's node affinity.`

`Node is not ready`

`Readiness probe failed:  `

`Liveness probe failed: `

## Acceptance Criteria

Ability to ignore pods by event.reason using custom yaml file.

**Comment by pkosiec** [comment]
Hey @AliHas78, please upgrade to the latest Botkube version and use event constraints for Kubernetes source. See the docs here: https://docs.botkube.io/configuration/source/kubernetes#event-and-resource-constraints

Hope that fixes your problem. If not, feel free to reopen this. Cheers!
