### ISSUE TITLE
Silence alerts that are false positive within Slack

### ISSUE THREAD

**Issue by AliHas78** [kubeshop/botkube#764]
## Overview

Currently we get pod errors that spam our slack channel and are false positive. We should have an option to ignore these error to rule out false positive.

## Acceptance Criteria

Ability to ignore alerts that are false positive from slack channel.

**Comment by pkosiec** [comment]
Hi @AliHas78, in Botkube 1.0+ we have a mechanism to exclude messages based on type, reason, message regex etc. I hope this will be helpful for you: https://docs.botkube.io/configuration/source/kubernetes

Please upgrade to the latest Botkube and try these features. If you'll be missing anything, feel free to reopen the issue. Cheers!
