### ISSUE TITLE
Rebrand Botkube

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube#785]
## Overview

We have a new branding 🥳  Time to apply it everywhere.

## Acceptance Criteria

- [x] Replace casing on both `botkube` and `botkube-docs` repos: `BotKube` -> `Botkube`
- [x]Update logo on `botkube` repo (get the latest assets from @lpetkov - logo, color styleguide)
- [x] Update logo and casing across all social media (Twitter, YouTube, LinkedIn etc.) + Slack workspace (sync up with @brampling)
- [x] Apply new branding on website:
   - [x] Change logo and favicons
   - ❌ Change look & feel (colors and font)
   - [x] Sync up with @lpetkov when it comes to design adjustments (to make it look close to the new marketing website)
- If the marketing website as ready to publish:
   - [x] Reconfigure docs website for the new marketing website - https://github.com/kubeshop/botkube-docs/pull/158
   - [x] Test the marketing website under a subdomain first
   - [x] Make sure it's zero downtime
   - [x] Remove homepage if the marketing website is ready - https://github.com/kubeshop/botkube-docs/pull/158
   - [x] redirect `botkube.io/docs` to `docs.botkube.io/`
   - [x] add Docusaurus redirect `botkube.io/filters` to `botkube.io/docs/filters` or somewhere else
   - [x] Links in the footer should have target="_blank" (Chris - https://kubeshop.atlassian.net/browse/DESIGN-385)

## Reason

Botkube's branding has been refreshed 🥳

**Comment by madebyrogal** [comment]
After call with @lpetkov we decided not to do big designs adjustments at least for now. Lacho will focus on WebApp
About updating logo in all social medias @brampling and Kelly have access to the accounts I support them in some resizing or adapting assets.

**Comment by madebyrogal** [comment]
Let me know what do you think about it?
https://kubeshop.slack.com/archives/C03MRCX7UE9/p1666717174473549
