### ISSUE TITLE
Botkube Automation

### ISSUE THREAD

**Issue by brampling** [kubeshop/botkube#789]
A user must be able to configure an automation action based on a selected incoming event. This allows the user to perform automatic problem resolution, automatically initiate early troubleshooting steps, and otherwise enhance their time to recovery when an issue occurs. Currently users are notified of events through a configured channel and must take all action manually either through Botkube or through other CLI and UI-based tools.

**AC**

- Users can configure Botkube to watch for a specific event type
- Users can filter the watched events
- Users can configure an executor action to trigger on the selected/filtered event (in other words, a given event triggers a given executor command).
- Relevant event details and metadata are passed to the executor action (i.e. pod name on a pod-related event)
- Configured actions are executed when the configured event occurs
- A notification is sent to the appropriate channel when an automated action occurs (ideally through the k8s event system and not only through Botkube, so that the event is logged in the k8s infrastructure)
- Configured actions can be enabled/disabled dynamically through chat commands (e.g. `@Botkube list/enable/disable automations`)
- Consult the configuration draft with @lpetkov

**Comment by pkosiec** [comment]
## Notes

- Executed command could be defined in config as a Go template string, rendered with `events.Event` object in context:

    ```
    # (...) for a given event the following command will be executed:
    command: "kubectl get {{.Event.ResourceType}} -m {{.Event.Namespace}} {{.Event.Name}}" # namespace and name are from the `Event` object
    ```

- The output is sent to the channel with a header that the command was executed by automation rule.

**Comment by ezodude** [comment]
In the acceptance criteria:

> Users can filter the watched events

I'm not sure what this means.

**Comment by brampling** [comment]
For example, the previous AC means we would watch for "pod create" events. This AC means I can filter those pod create events. Maybe I only want to trigger on a pod create matching a specific name pattern, or a specific annotation.

**Comment by ezodude** [comment]
@brampling added a ticket to cover this: https://github.com/kubeshop/botkube/issues/832
