### ISSUE TITLE
Prepare demo environment and demo scenarios for Kubecon

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube#792]
## Description

As we'll be both live and virtually on Kubecon, we want to make sure we have demos ready to showcase for the booth visitors.

## AC

- [x] Coordinate the prep work for demos
    - Ensure we have looping video for the booth
    - Ensure we have presenters for demos on the virtual booth (contact DevRel to get details of our virtual booth attendance)
- [x] Create a long-running cluster for demos @pkosiec 
    - As Blair suggested, we could use https://github.com/jpetazzo/ampernetacle (tried it yesterday, personally I had issues with CNI misconfigured, I'd need to investigate it) or https://github.com/garutilorenzo/k3s-oci-cluster (didn't try this one)
    - Install BotKube
    - Use e.g. Terraform and store the state to make sure we can cleanup it easily
    - Provide some short instruction how to quickly recreate it (it can be something existing out there, or just some snippets - nothing official)
    - **Cluster created + Slack and Discord workspaces set up - details on our private shared Google Drive and Slack**
- [x] Prepare demo scenarios for live and virtual booths
    - Generic demo - we can reuse something we already had (e.g. for the release livestream etc.).
    - Interactivity preview

## Reason

Kubecon 🥳

**Comment by mszostok** [comment]
Additional points, for creating **shared Botkube playground:**
- [ ] Connect it with public channel on Botkube Slack workspace 
- [ ] Do a dry-run with more users at the same time (maybe Kubeshopers could help us? so we can test how Botkube behaves when ~40 people are using it at the same time)
- [ ] We need to make sure that Botkube responses aren’t flaky
- [ ] Create an invite QR Code 
- [ ] Make sure that the QR Code will be later displayed on booth’s screens
    - Ask @lpetkov if he can create some graphic for that.
