### ISSUE TITLE
Using --cluster-name stops any responses

### ISSUE THREAD

**Issue by tim-sendible** [kubeshop/botkube#799]
## Description
```
BotKube version: v0.14.0
K8s Server Version: v1.23.10-eks-15b7512
Slack
```

We have multiple clusters running botkube, as as advised by the bot, we try to do commands in this manner:
`@botkube get pods --cluster-name=“myclustername”`
This results in no response.

If I do `@botkube get pods`, all clusters respond with the correct answer.

## Expected behavior

I should have a working mechanism to choose a call/response to a single botkube instance.

**Comment by pkosiec** [comment]
Hi @tim-sendible, thanks for reporting the issue.
Please try to do it without quotes:

```
@Botkube get pods --cluster-name myclustername
```

Does it work for you? I've just tested it and was able to get a proper response.

**Comment by tim-sendible** [comment]
The bot tells me to use quotes:
![image](https://user-images.githubusercontent.com/69461449/194546146-57b907d1-b12c-46e9-9c8c-2b0f9d2c3aa3.png)

But yes, not using quotes works.

**Comment by pkosiec** [comment]
Oh, you're right, this is something which should be fixed. I'll do that later next week 👍 Thanks for reporting it!
