### ISSUE TITLE
Interactive filtering in thread does not show filter results in thread

### ISSUE THREAD

**Issue by ezodude** [kubeshop/botkube#816]
## Description

When using interactive `kubectl` with filtering in Slack. Botkube replies with the results and starts a thread to allow for running other filters.

When using this thread to run the filter, filtered results appear in the main section of the channel and NOT in the thread. This is confusing because in the first instance you think filtering is not working.

See this screenshot:

<img width="1028" alt="filter_thread_bug" src="https://user-images.githubusercontent.com/105397/196121164-367c1ca0-3ad9-44aa-9333-de54b1909d9c.png">

## Expected behavior

Further filtered messages should appear in the thread.

## Actual behavior

Further filtered messages are appearing the channel's main section.

## Steps to reproduce

- Set up Botkube in Slack.
- Run `@Butkube kc` to start interactive `kubectl`.
- Add a filter in the filter input box.
- Enter the started thread.
- Add another filter text and hit enter.
- The filter result will show in the main channel section instead of the thread.

**Comment by huseyinbabal** [comment]
I reproduced this for interactive commands, but not with the normal ones. So, If I start with `Botkube kc`, this issue happens, but if I type `Botkube describe nodes` and continue, it works as expected. See below.

**With `@Botkube kc`**

![Screen Shot 2022-10-17 at 14 44 49](https://user-images.githubusercontent.com/1237982/196169091-59f676d6-7ca1-4211-8b6a-2da2321328e2.png)


**With `@Botkube describe nodes**

![Screen Shot 2022-10-17 at 14 46 31](https://user-images.githubusercontent.com/1237982/196169413-d7ecf2fd-a197-4915-8cb4-92745a2087f2.png)
