### ISSUE TITLE
Release BotKube 0.15

### ISSUE THREAD

**Issue by ezodude** [kubeshop/botkube#825]
## Overview

This task aggregates all the to-dos which should be done when it comes to 0.15 release.

## AC
- [x] Go through the release process instruction and release 0.15
 ~Describe any breaking changes in the GitHub release~ **There are none**.
- [x] Testing
    - Test manually interactivity for Slack
    - Test telemetry
    - Aggregate all stuff for manual testing described by @mszostok in https://github.com/kubeshop/botkube/issues/595
- [x] Schedule all community activities - blog post, sharing the news in social media, livestream, etc. (@brampling)

**Comment by ezodude** [comment]
Bugs:

- [ ] Slack UI does not wrap filter values in quotes.

<img width="512" alt="Screenshot 2022-10-20 at 13 16 51" src="https://user-images.githubusercontent.com/105397/196947963-98f84aab-80fe-4ab1-9b3c-3eff8001e47e.png">

**Comment by huseyinbabal** [comment]
Ok created PR [here](https://github.com/kubeshop/botkube/pull/826)

**Comment by ezodude** [comment]
So far, all release candidate required fixes have been addressed in PR: https://github.com/kubeshop/botkube/pull/826
