### ISSUE TITLE
Add node count to telemetry

### ISSUE THREAD

**Issue by brampling** [kubeshop/botkube#836]
A count of nodes within a given cluster must be sent to telemetry. This can be done in the `identify` call.

**AC**
- Cluster node count is available in telemetry data for each reporting cluster

**Comment by pradeepnnv** [comment]
I would like to contribute for this issue.

**Comment by pkosiec** [comment]
Sure @pradeepnnv, feel free to take this!
The nodes count should be included here in the Identity struct as another trait: https://github.com/kubeshop/botkube/blob/main/internal/analytics/identity.go
It should be fetched from the cluster using k8s CLI in this method: https://github.com/kubeshop/botkube/blob/838584382158e93a48734e41c1e888add8507fa1/internal/analytics/segment_reporter.go#L176

Ideally, you could count worker and control plane nodes separately.
Let me know if you need any help. Thank you!

**Comment by pkosiec** [comment]
Hey @pradeepnnv how it's going? Do you have any questions related to this task? Let us know 🙂

**Comment by pradeepnnv** [comment]
HI @pkosiec,

Thanks for being patient.
This is what I'm planning to update. https://github.com/pradeepnnv/botkube/commit/821caaedc31633124f0bccd935223e75f2e2981e
Still working on the tests though. Please review and let me know if my approach is ok.

**Comment by pkosiec** [comment]
Hey @pradeepnnv, thank you. It looks good!
Could you please add a small change to count worker and control plane nodes separately? Something like:

```go
	list, err := k8sCli.CoreV1().Nodes().List(ctx, metav1.ListOptions{})

	var (
		controlPlaneNodesCount int
		workerNodesCount int
	)
	for _, item := range list.Items {
		val, ok := item.Labels[kubeadmconstants.LabelNodeRoleControlPlane]
		if !ok || val != "true" {
			workerNodesCount++
			continue
		}

		controlPlaneNodesCount++
	}

```

I used constant from the import: `kubeadmconstants "k8s.io/kubernetes/cmd/kubeadm/app/constants"` - https://github.com/kubernetes/kubernetes/pull/95382.
You'll need to add `k8s.io/kubernetes v1.25.0` to dependencies in `go.mod`.

Thanks a lot!

**Comment by pradeepnnv** [comment]
Thanks @pkosiec .  Pushed the latest changes. https://github.com/pradeepnnv/botkube/commit/087c262f37a36ff132712ca244004882dc007d73
I had issues when importing kubeadmconstants. Had to apply the fix suggested in https://github.com/kubernetes/kubernetes/issues/79384#issuecomment-521493597. 
Please review.

Also, still not able to make the test TestSegmentReporter_RegisterCurrentIdentity pass. Analyzing further.

**Comment by pkosiec** [comment]
Hey @pradeepnnv, it looks really nice 👍 Yesterday I was able to avoid the problems (and the script. What I did is:

1. Add import to `segment_reporter.go`
2. Add in the `go.mod` `require` section:

```
	k8s.io/kubernetes v1.25.0
	k8s.io/cluster-boostrap v0.25.0
```

3. Run `go mod tidy` and `go mod download`.

Please check if that helps, and please remove the script and all the `replace` directives. Thanks a lot!

If you'd like some help with tests, please open the PR and I'll be able to help there with some suggestions etc. 🙂 Remember that we use golden files in parts of our tests, so as the comment says:

```go
// The analytics.SegmentReporter tests in the `analytics_test` package is based on golden file pattern.
// If the `-test.update-golden` flag is set then the actual content is written
// to the golden file.
//
// To update golden files, run:
//
// go test ./internal/analytics/... -test.update-golden
``` 

But it would be great to add ~3 sample nodes to the fake K8s client and see if we get the count properly. Thank you!

**Comment by pradeepnnv** [comment]
@pkosiec , created PR https://github.com/kubeshop/botkube/pull/853. Please review.
