### ISSUE TITLE
Add plugin manager to Botkube

### ISSUE THREAD

**Issue by huseyinbabal** [kubeshop/botkube#838]
## Overview

Plugin manager is responsible for handling plugin registration based on the configuration of each plugin. We need to  implement that in Botkube as described in AC

## Acceptance Criteria
-  Plugin manager can accept plugin configuration with name and version.

- Plugin manager can accept plugin configuration with name and version
- It should download the plugin executable by using the name and version to a specified local folder before running the Botkube application
- There should be a caching mechanism not to download same version again
- You can see a working example [here](https://github.com/huseyinbabal/botkube-plugins-playground/blob/main/plugin/manager.go)

**Comment by mszostok** [comment]
- [ ] Add executor plugin manager with example executor
- [ ] Add source plugin manager with example source
- [ ] Add validation according to [Validating Plugin configuration](https://github.com/kubeshop/botkube/blob/main/docs/proposal/2022-11-22-botkube-plugins-integration.md#validating-plugin-configuration)
- [ ] Add logger for go-plugin client
   - We need to create a wrapper for [plugin binary output](https://github.com/hashicorp/go-plugin/blob/b60690f8999f79dae652a67e7b81a6923b43cff8/client.go#L161-L166) and the [plugin client](https://github.com/hashicorp/go-plugin/blob/b60690f8999f79dae652a67e7b81a6923b43cff8/client.go#L181-L183) itself
- [ ]
