### ISSUE TITLE
Document plugins

### ISSUE THREAD

**Issue by huseyinbabal** [kubeshop/botkube#839]
## Overview

Write documentation that describes how to implement a source or executor plugin.

## Acceptance Criteria

- Document plugin management for the end-user
   - State that the only the plugins from our repo are safe (recommended)
- Update configuration for "default" sources and executors
- Prepare documentation for adding new plugins to Botkube
    - It should contain how to verify plugin functionality in PR checks
    - Boilerplate template for plugin development. Please refer [here](https://github.com/huseyinbabal/botkube-plugins/tree/main/plugins/kubectl) for an example
    - Once needed, provide a mocking mechanism to write tests for specific plugin
    - You can see the filters docs: https://docs.botkube.io/usage/filters/development
    - You can use echo executor etc.
    - Rules about accepting plugins to our repo

## Reason

#844 

Related:

#925

**Comment by mszostok** [comment]
The Botkube architecture doc was updated in this PR: https://github.com/kubeshop/botkube-docs/pull/187
