### ISSUE TITLE
Extract Kubectl executor feature as a plugin

### ISSUE THREAD

**Issue by huseyinbabal** [kubeshop/botkube#841]
## Overview

Botkube supports `kubectl` execution and it is a typical Executor plugin. We need to extract it as a standalone plugin.

## Acceptance Criteria

- Extract `kubectl` executor as a plugin and maintain it Botkube main repository
- Ensure it is backward compatible.
- Plugin parameters will be documented in the plugin's README.md page, and they can be provided from Botkube as an environment variable like `KUBERNETES_...` so that they can be passed to the executable [in this line](https://github.com/huseyinbabal/botkube-plugins-playground/blob/c85cb7b84296a2f41c2dcdd8cac77c0e9dd9c69a/plugin/manager.go#L159)
- Remember about interactivity
- Update gRPC executor API
- Make sure anonymized telemetry is still supported - we can lose some data, but confirm with @brampling if we can do that
- Update the document

## Additional scope / notes
- Ensure it supports the RBAC design according to #712 (design https://github.com/kubeshop/botkube/blob/main/docs/proposal/2022-12-23-rbac.md), if #934 is already done. If not, ensure we can easily support this in the plugin.

**Comment by pkosiec** [comment]
See @mszostok's PR: https://github.com/kubeshop/botkube/pull/857

**Comment by mszostok** [comment]
Implementation:
- https://github.com/kubeshop/botkube/pull/973
- https://github.com/kubeshop/botkube/pull/982
- https://github.com/kubeshop/botkube/pull/986

Docs:
- https://github.com/kubeshop/botkube-docs/pull/213
- https://github.com/kubeshop/botkube-docs/pull/215
