### ISSUE TITLE
Helm as alternative executor plugin

### ISSUE THREAD

**Issue by huseyinbabal** [kubeshop/botkube#843]
## Overview

Botkube has existing support for `kubectl`, now we will be adding helm support to execute helm commands through Botkube.

## Acceptance Criteria

- [x] Helm executor plugin should have the same experience (commands, flags) as Helm CLI
- [x] Implement Helm plugin for Botkube
    - interactivity is out of scope
    - install, uninstall, upgrade, rollback, list, version, test, status
       - `--repo` - custom flag which adds the repo for a short period of time
       - support `--set` for now
       - ensure multiline commands work properly
- [x] Design a configuration structure for the helm executor plugin
- [x] Document it in plugins folder under the main Botkube repository.

Stretch:

- [ ] add `helm history` command
- [ ] add `helm get [all|manifest|hooks|notes]` commands
## Reason

Helm support was heavily requested by the community. That's why this would be one of the first new executors.

**Comment by brampling** [comment]
We don't need to support all of the commands that are used for creating Helm charts. We should support the commands used for working with software installed using Helm (show, install, uninstall, upgrade, rollback, etc.).

**Comment by mszostok** [comment]
@brampling @lpetkov 

Do we want to add a Helm related section to our Help message? _(visible only when Helm plugin is enabled)_
Something similar to what we have for `kubectl`?
<img width="818" alt="Screen Shot 2022-12-21 at 23 29 10" src="https://user-images.githubusercontent.com/17568639/209014582-54e6bfe2-1ed5-412d-9890-764e60198aea.png">

**Comment by mszostok** [comment]
Stretch:
- add `history` command
- add `helm get [all|manifest|hooks|notes]` commands

**Comment by brampling** [comment]
Yes, this would be nice to add for now. If we eventually get lots of plugins we should make it generic, but in this version it's useful to get users to try the new feature.
