### ISSUE TITLE
Delete Heroku stack

### ISSUE THREAD

**Issue by brampling** [kubeshop/botkube#846]
We are currently using the Heroku-18 stack for the [botkube](https://dashboard.heroku.com/apps/botkube) and [botkube-slack](https://dashboard.heroku.com/apps/botkube-slack) apps. These need to be upgraded to Heroku-22 because Heroku-18 is deprecated and will stop receiving security patches on April 30, 2023.

**AC**
- Remove Heroku apps
  - Remove Slack inviter and replace it with Shared invite
    - Detect the invitation is outdated or Automate to replace the invite
  - Remove the Python app to process the legacy Slack installations
- Let know @brampling to close the account

- ~Remove legacy Botkube app from Slack directory~ more info here: https://kubeshop.slack.com/archives/C03MRCX7UE9/p1694706282530529
- Remind @mashby, Website team and everyone to always use `join.botkube.io` for community Slack invitations

**Comment by pkosiec** [comment]
Probably we can remove all the apps by the end of April as we won't support new legacy Slack installations. And we will switch to Slack shared invite for workspace invitiations.

AI: Revisit this by the end of Feburary.

**Comment by pkosiec** [comment]
Revisit it after https://github.com/kubeshop/botkube/issues/865

**Comment by mszostok** [comment]
## Notes

To create a new invite click Botkube, next "Invite people to Botkube"

![Image](https://github.com/kubeshop/botkube/assets/17568639/e87db1fe-459b-48e5-bc41-1dba912dc521)

Under "Edit link", select "Never expires"

![Image](https://github.com/kubeshop/botkube/assets/17568639/71ca5037-9394-4479-9d35-09f825e731e7)

---

Current invite URL: https://join.slack.com/t/botkube/shared_invite/zt-23iwxume8-gVbHInBtANXmtwYoKznlDQ
