### ISSUE TITLE
Add support for rollout restart

### ISSUE THREAD

**Issue by dinodam** [kubeshop/botkube#847]
## Overview

Support for rollout restart in verion 0.15.0

## Acceptance Criteria

To be able to restart deployments from @botkube

## Reason

With automation of botkube coming up, it would be nice to be able to restart deployments automagically from the Botkube bot.

**Comment by pkosiec** [comment]
This should be possible once we implement #841 and #675 (initially planned for 0.19), as we won't need to validate each command manually 🙂

**Comment by pkosiec** [comment]
Closing as it is already implemented on `main`. The new Botkube release is coming really soon (next week!) 🚀
