### ISSUE TITLE
Prometheus as alternative source plugin

### ISSUE THREAD

**Issue by brampling** [kubeshop/botkube#849]
A user must be able to source events from Prometheus in order to receive notifications about important cluster state issues and other alerts triggered in Prometheus.

**AC**
- Botkube can source events from Prometheus via Alertmanager
- Botkube shows important alerts (e.g. kube-state-metrics node CPU/memory alarms) collected by Prometheus/Alertmanager

**Reason**
Botkube needs to be capable of showing events from within a K8s cluster beyond those in the K8s event stream. These include alerts on node health (CPU/memory usage, etc.), alerts from kube-state-metrics, and others.

**Comment by huseyinbabal** [comment]
@brampling I implemented initial working plugin of Prometheus, and need some clarifications about following item.
- I am using alert manager API, and there is no date filter there but I have a filtering mechanism on plugin side that shows only new alarms on Botkube, and does not send same alarm to Botkube twice. So, do we want to show only negative statuses or do you want to see also alarms that converted from firing -> to pending, pending -> to success?

**Comment by huseyinbabal** [comment]
> @huseyinbabal Ideally we would make that configurable. Is it a lot of additional work?

I will more details then :) What kind of config will it be, list of status to be reported?

**Comment by huseyinbabal** [comment]
Ok I implemented this,
![Screen Shot 2023-01-17 at 12 32 16](https://user-images.githubusercontent.com/1237982/212861493-e7164f15-e2bc-4e82-a548-9a120040a3a1.png)
