### ISSUE TITLE
Missing readiness probe for GKE/Ingress integration

### ISSUE THREAD

**Issue by mirkosertic** [kubeshop/botkube#881]
## Description

We want to use BotKube with MS Teams integration. We do have an existing K8s cluster running on GKE, and we want to expose the BotKube API over an existing GKE Ingress instance. However, GKE Ingress seems to require an HTTP Probe returning 200 for Ingress backend readiness check. Unfortunately, we cannot find a documentation or way to use the BotKube container for that purpose,

## Expected behavior

The BotKube container provides a readiness probe that can also be used for Ingress backend healthchecks.

## Actual behavior

There seems to be no probe in the current BotKube container image,

**Comment by mszostok** [comment]
Hi @mirkosertic 

You are right. I checked and we don't have any healthcheck endpoint exposed from Botkube container.


I see two options:
- add global healthcheck e.g. `{host}:{botkube_port}/healthz` so we can also utilize that on `liveness` probe for Botkube itself.
- add a dedicated MS Teams healthcheck e.g. `{host}:{ms_teams_port}/bots/teams/heathcheck`
@pkosiec any thoughs?

We will try to incorporate that into the current release to make it available as soon as possible.

**Comment by mszostok** [comment]
Summary after dev-team meeting:

- Introduce Botkube `healthz` endpoint that returns the 200 (OK). 
- Later we will maybe return JSON with information about Botkube core health
  - and enabled plugins (after https://github.com/kubeshop/botkube/issues/878)
  - and communications platform status (is it possible?)
