### ISSUE TITLE
Incorrect Elasticsearch Index Mapping

### ISSUE THREAD

**Issue by josefkarasek** [kubeshop/botkube#919]
## Description

Writing data to elasticsearch fails with `mapper_parsing_exception`. 
This means that the data we're trying to send doesn't correctly map to the index configuration we created earlier for botkube es index.

## Expected behavior

Elasticsearch integration works. Botkube can connect to Elasticsearch, can create index and index mapping and correctly sends data to Elasticsearch.

## Actual behavior

Elasticsearch integration does not work.
Error is encoutered when trying to send data to Elasticsearch.

```
error occurred:\n\t* while sending event to Elasticsearch index \"botkube\":
while posting data to ELS: elastic: Error 400 (Bad Request):
failed to parse [type=mapper_parsing_exception]"
component=Controller
```

## Steps to reproduce

Deploy Elasticsearch and Botkube wit ES sink enabled based on [docs](https://docs.botkube.io/community/contribute/elasticsearch-develop/).

Fire an event: `kubectl run nginx --image=nginx`

**Comment by pkosiec** [comment]
It could be because Botkube sends the whole event.Event object to elasticsearch. We should ignore not supported fields - possibly the event object was modified with some new fields?
