### ISSUE TITLE
Unable to issue helm upgrade for v0.17.0

### ISSUE THREAD

**Issue by magandrez** [kubeshop/botkube#937]
## Description

I am attempting to upgrade my botkube deployment in a GKE cluster (running its own namespace and installed with `helm` according to the latest instructions still up in the documentation).

However, I am unable to upgrade, (possibly due to not understanding helm's interface, but no upgrade instructions in Botkube are available either).

## Expected behavior

I expect to upgrade botkube with helm issuing something like:

`$ helm repo update`

followed by something like:

`$ helm upgrade botkube botkube/v0.17.0`

would upgrade the current installed version of Botkube in the cluster. Default values from the chart are just fine by me.

## Actual behavior

_computer says no_

Repo is in its place:

```
$ helm repo list
NAME            URL
botkube         https://charts.botkube.io
```
and v0.16.0 deployed and running

```
$ helm list
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
botkube botkube         1               2022-12-28 09:35:23.153068982 +0200 EET deployed        botkube-v0.16.0 v0.16.0
```

## Steps to reproduce

```
$ helm repo update && helm upgrade botkube botkube/v0.17.0 --debug
Error: chart "v0.17.0" matching  not found in botkube index. (try 'helm repo update'): no chart name found
helm.go:84: [debug] no chart name found
[clipped trace]
```

**Comment by magandrez** [comment]
For completeness, I tried the following variations:

```
$ helm upgrade botkube botkube/v0.17.0 --debug
helm upgrade botkube botkube/botkube.v0.17.0 --debug
helm upgrade botkube botkube/botkubev0.17.0 --debug
helm upgrade botkube botkube/botkube-v0.17.0 --debug
helm upgrade botkube botkube.io/botkube-v0.17.0 --debug
helm upgrade botkube charts.botkube.io/botkube-v0.17.0 --debug
helm upgrade botkube botkube-v0.17.0 --debug
helm upgrade botkube v0.17.0 --debug
helm upgrade botkubev0.17.0 --debug
helm upgrade botkube
helm upgrade botkube botkube/botkube:v0.17.0 --debug
helm upgrade botkube infracloudio/botkube:v0.17.0 --debug
helm upgrade botkube botkube:v0.17.0 --debug
helm upgrade botkube/botkube kubeshop/botkube:v0.17.0 --debug
helm upgrade botkube/botkube ghcr.io/kubeshop/botkube:v0.17.0 --debug
helm upgrade botkube/botkube kubeshop/botkube-v0.17.0 --debug
helm upgrade botkube/botkube https://charts.botkube.io/botkube-v0.17.0 --debug
helm upgrade botkube/botkube https://charts.botkube.io/v0.17.0 --debug

**Comment by pkosiec** [comment]
Hi @magandrez,
The version should be provided with `--version` flag. This works for me:

```bash
helm repo update
helm install botkube --version v0.16.0 --namespace botkube botkube/botkube --create-namespace
helm upgrade botkube -n botkube --version v0.17.0 botkube/botkube
```

Let me know if you have any other questions 🙂

**Comment by magandrez** [comment]
> Hi @magandrez,
> 
> The version should be provided with `--version` flag. This works for me:
> 
> 
> 
> ```bash
> 
> helm repo update
> 
> helm install botkube --version v0.16.0 --namespace botkube botkube/botkube --create-namespace
> 
> helm upgrade botkube -n botkube --version v0.17.0 botkube/botkube
> 
> ```
> 
> 
> 
> To learn more about the `helm upgrade` command, see the official docs here: https://helm.sh/docs/helm/helm_upgrade/.
> 
> Let me know if you have any other questions 🙂 

![](https://giphy.com/gifs/wetv-no-facepalm-cant-3xz2BLBOt13X9AgjEA)



Thanks!!

**Comment by pkosiec** [comment]
😄 No problem at all, glad it finally worked!
