### ISSUE TITLE
Muting certain events

### ISSUE THREAD

**Issue by MOZGIII** [kubeshop/botkube#954]
## Overview

I am looking for a way to mute certain events at the source level. I found that I can write a regex for `event.message` to filter the events, but the Go regex engine does not allow for negative lookahead/lookbehind, so writing and maintaining the right regex to allow everything except what I want to filter becomes a mess.

It would be nice if I could write a negative filter, to allow anything except for what is matched by the criteria.

## Acceptance Criteria

- Allow negative filters on `event.message` and `event.kind`.
- When the criteria matches, the event is ignored, when the criteria does not match the event is processed.

## Reason

We need a way to ignore certain cluster events, but allow everything else.

**Comment by brampling** [comment]
Hi @MOZGIII, thanks for the opening the issue. This is something I also ran into while writing some documentation for Botkube. It's definitely something we need to address and we will look into the best way to implement it.

**Comment by pkosiec** [comment]
Hi 👋 I'm going to check if a different regex engine (https://github.com/dlclark/regexp2) which supports positive/negative lookahead/lookbehind will do the trick. If yes, it will be fairly easy to implement 🤞Will post an update tomorrow. Cheers!

**Comment by MOZGIII** [comment]
> Hi 👋 I'm going to check if a different regex engine ([dlclark/regexp2](https://github.com/dlclark/regexp2)) which supports positive/negative lookahead/lookbehind will do the trick. If yes, it will be fairly easy to implement 🤞Will post an update tomorrow. Cheers!

It would be better to implement negating filter with a separate regex. There are very practical reasons to not have lookahead/behind in a regex parser, an in this case it can easily be worth a substantial (i.e. more than ~x2) CPU load increase for the same work. It is also more difficult to maintain a lookahead/behind regex than a usual one.

**Comment by pkosiec** [comment]
Thanks for feedback @MOZGIII. After discussing that f2f inside our team we agreed to go with the Go builtin regex engine and support `include/exclude` list of regexes, similarly to what we have in the `sources[name].kubernetes.namespaces`. However, as we're going to publish 0.18RC1 today, I'm afraid it will be moved to the 0.19 release.

**Comment by pkosiec** [comment]
Hey @MOZGIII, the PR #211 was merged and this functionality will be included in 0.19.
See the updated docs here: https://docs.botkube.io/next/configuration/source/kubernetes#event-and-resource-constraints 

You can also try out the unstable `main` version if you'd like to 🙂
