### ISSUE TITLE
Blog Post after 1.0.0 release

### ISSUE THREAD

**Issue by brampling** [kubeshop/botkube#961]
_(description copied from the comment)_

## AC
- Create blog post in Markdown, but have in mind it will be posted on Webflow, so don't use too complicated syntax 😅 
    - Sync with @mszostok how to convert it to Webflow format  
- Cross post to Medium / Dev.to
Topic Ideas:
- How to write own Prometheus plugin - figure out a simple and cool source plugin
   - Azure source?
   - See other ideas on [Slack](https://kubeshop.slack.com/archives/C03MRCX7UE9/p1674219772941149)
- Idea: publish it after 0.19 release so that we can use new API

Putting timebox of 3MD

### Update: 
Blog post is available here https://botkube.io/blog/implementing-your-own-botkube-plugin-a-real-life-use-case

**Comment by pkosiec** [comment]
@brampling could you please elaborate a bit more about the expectations? What topic should we cover?


## AC
- Create blog post in Markdown, but have in mind it will be posted on Webflow, so don't use too complicated syntax 😅 
- Cross post to Medium / Dev.to
Topic Ideas:
- How to use Prometheus plugin
- How to write your own source plugin - figure out something simple and cool
- See other ideas on [Slack](https://kubeshop.slack.com/archives/C03MRCX7UE9/p1674219772941149)

Putting timebox of 3MD

**Comment by huseyinbabal** [comment]
Blog post is ready here https://github.com/kubeshop/botkube/pull/1050 . Will convert to webflow soon.

**Comment by huseyinbabal** [comment]
It is now available on Webflow here https://botkube.io/blog/implementing-your-own-botkube-plugin-a-real-life-use-case
